/* =========================================================
   Answer key, levels 1–5 — one entry per correct sentence (plain text, no [ ])
   tt  Thai translation of the correct sentence
   en  why: what makes it correct and what was wrong with the broken version
   th  the same explanation in Thai
   ========================================================= */
const ANSWERS = {
  /* ---- 1 Nouns ---- */
  'I have two cats.': { tt:'ฉันมีแมวสองตัว',
    en:'Two cats = more than one, so the noun needs -s: cat → cats.', th:'แมวสองตัว = มากกว่าหนึ่ง คำนามจึงต้องเติม -s: cat → cats' },
  'Three children are playing.': { tt:'เด็กสามคนกำลังเล่นอยู่',
    en:'"child" has a special plural: children. "childs" is not a word.', th:'child มีรูปพหูพจน์พิเศษคือ children ไม่มีคำว่า childs' },
  'She bought five boxes.': { tt:'เธอซื้อกล่องห้าใบ',
    en:'Nouns ending in -x add -es: box → boxes.', th:'คำนามที่ลงท้ายด้วย -x ต้องเติม -es: box → boxes' },
  'The mice ate the cheese.': { tt:'หนูกินชีสไปแล้ว',
    en:'"mouse" has a special plural: mice. "mouses" is wrong.', th:'mouse มีรูปพหูพจน์พิเศษคือ mice ไม่ใช่ mouses' },
  'I need some information.': { tt:'ฉันต้องการข้อมูลบางอย่าง',
    en:'"information" can\'t be counted, so it never takes -s.', th:'information เป็นคำนามนับไม่ได้ จึงเติม -s ไม่ได้เลย' },
  'My teeth are white.': { tt:'ฟันของฉันขาว',
    en:'"tooth" has a special plural: teeth. "tooths" is wrong.', th:'tooth มีรูปพหูพจน์พิเศษคือ teeth ไม่ใช่ tooths' },
  'I live in Bangkok.': { tt:'ฉันอาศัยอยู่ที่กรุงเทพฯ',
    en:'Bangkok is the name of a place, so it starts with a capital B.', th:'Bangkok เป็นชื่อเฉพาะของสถานที่ ต้องขึ้นต้นด้วยตัวพิมพ์ใหญ่ B' },
  "This is Tom's bike.": { tt:'นี่คือจักรยานของทอม',
    en:'To show who owns something, add \'s: Tom\'s bike = the bike that belongs to Tom.', th:'แสดงความเป็นเจ้าของให้เติม \'s: Tom\'s bike = จักรยานของทอม' },
  'He has a dog.': { tt:'เขามีสุนัขหนึ่งตัว',
    en:'One countable thing needs a or an in front of it: a dog.', th:'คำนามนับได้ที่มีหนึ่งเดียว ต้องมี a หรือ an นำหน้า: a dog' },
  'Two women are waiting.': { tt:'ผู้หญิงสองคนกำลังรออยู่',
    en:'"woman" has a special plural: women. "womans" is wrong.', th:'woman มีรูปพหูพจน์พิเศษคือ women ไม่ใช่ womans' },
  'The leaves are falling.': { tt:'ใบไม้กำลังร่วง',
    en:'Many words ending in -f change to -ves: leaf → leaves.', th:'คำที่ลงท้ายด้วย -f หลายคำเปลี่ยนเป็น -ves: leaf → leaves' },
  'Money cannot buy happiness.': { tt:'เงินซื้อความสุขไม่ได้',
    en:'After "buy" we need a thing (a noun): happiness. "happy" is an adjective.', th:'หลัง buy ต้องเป็นสิ่งของ (คำนาม) คือ happiness ส่วน happy เป็นคุณศัพท์' },

  /* ---- 2 Pronouns ---- */
  'She is my teacher.': { tt:'เธอเป็นครูของฉัน',
    en:'She does the action (before the verb), so use "She". "Her" is used after a verb.', th:'เธอเป็นผู้ทำ (อยู่หน้ากริยา) จึงใช้ She ส่วน her ใช้หลังกริยา' },
  'Tom likes her.': { tt:'ทอมชอบเธอ',
    en:'After the verb "likes" use the object form: her, not she.', th:'หลังกริยา likes ต้องใช้รูปกรรม her ไม่ใช่ she' },
  'Can you help me?': { tt:'คุณช่วยฉันได้ไหม?',
    en:'After the verb "help" use the object form: me, not I.', th:'หลังกริยา help ต้องใช้รูปกรรม me ไม่ใช่ I' },
  'This book is mine.': { tt:'หนังสือเล่มนี้เป็นของฉัน',
    en:'No noun comes after it, so use "mine" (= my book). "my" needs a noun: my book.', th:'ไม่มีคำนามตามหลัง จึงใช้ mine (= my book) ส่วน my ต้องมีคำนามตาม เช่น my book' },
  'We are students.': { tt:'พวกเราเป็นนักเรียน',
    en:'We do the action (before the verb), so use "We". "us" is used after a verb.', th:'พวกเราเป็นผู้ทำ (อยู่หน้ากริยา) จึงใช้ We ส่วน us ใช้หลังกริยา' },
  'He hurt himself.': { tt:'เขาทำร้ายตัวเอง',
    en:'"Himself" is the -self word for "he". "hisself" is not a word.', th:'"ตัวเขาเอง" คือ himself ไม่มีคำว่า hisself' },
  'Give it to them.': { tt:'เอามันให้พวกเขา',
    en:'After "to" use the object form: them, not they.', th:'หลัง to ต้องใช้รูปกรรม them ไม่ใช่ they' },
  'They live near us.': { tt:'พวกเขาอาศัยอยู่ใกล้พวกเรา',
    en:'Before the verb use "They"; after "near" use the object form "us".', th:'หน้ากริยาใช้ They ส่วนหลัง near ใช้รูปกรรม us' },
  'Is this bag yours?': { tt:'กระเป๋าใบนี้เป็นของคุณหรือเปล่า?',
    en:'No noun comes after it, so use "yours". "your" needs a noun: your bag.', th:'ไม่มีคำนามตามหลัง จึงใช้ yours ส่วน your ต้องมีคำนามตาม เช่น your bag' },
  'The cat licked its paw.': { tt:'แมวเลียอุ้งเท้าของมัน',
    en:'"its" = belongs to it. "it\'s" means "it is", so "it\'s paw" would mean "it is paw".', th:'its = ของมัน ส่วน it\'s = it is ถ้าเขียน it\'s paw จะแปลว่า "มันคืออุ้งเท้า"' },
  'Anna and I went home.': { tt:'แอนนากับฉันกลับบ้าน',
    en:'"Anna and I" do the action, so use "I". Test it alone: "I went home", not "me went home".', th:'แอนนากับฉันเป็นผู้ทำ จึงใช้ I ลองตัดชื่อออกดู: I went home ไม่ใช่ me went home' },
  'We enjoyed ourselves.': { tt:'พวกเราสนุกกันเต็มที่',
    en:'"we" is plural, so the -self word is plural too: ourselves.', th:'we เป็นพหูพจน์ คำว่าตัวเองจึงต้องเป็นพหูพจน์ด้วย: ourselves ไม่ใช่ ourself' },

  /* ---- 3 Verbs ---- */
  'She goes to school.': { tt:'เธอไปโรงเรียน',
    en:'"She" in the present needs -s / -es on the verb: go → goes.', th:'ประธาน she ในปัจจุบัน กริยาต้องเติม -s / -es: go → goes' },
  "He doesn't like fish.": { tt:'เขาไม่ชอบปลา',
    en:'"He" uses doesn\'t (does not), not don\'t.', th:'ประธาน he ใช้ doesn\'t ไม่ใช่ don\'t' },
  'I agree with you.': { tt:'ฉันเห็นด้วยกับคุณ',
    en:'"agree" is already a verb. Don\'t put "am" in front of it.', th:'agree เป็นกริยาอยู่แล้ว ห้ามมี am นำหน้า' },
  'She can swim very well.': { tt:'เธอว่ายน้ำเก่งมาก',
    en:'After "can" use the base verb: swim (no -s).', th:'หลัง can ใช้กริยาช่อง 1 ไม่เติม -s: swim' },
  'Yesterday I ate rice.': { tt:'เมื่อวานฉันกินข้าว',
    en:'"Yesterday" is in the past, so use verb 2: eat → ate.', th:'Yesterday เป็นอดีต ต้องใช้กริยาช่อง 2: eat → ate' },
  'They are my friends.': { tt:'พวกเขาเป็นเพื่อนของฉัน',
    en:'"They" is more than one person, so use "are", not "is".', th:'They เป็นพหูพจน์ ต้องใช้ are ไม่ใช่ is' },
  'We went to the zoo last week.': { tt:'เราไปสวนสัตว์เมื่อสัปดาห์ที่แล้ว',
    en:'"go" is irregular: its past is "went". "goed" is not a word.', th:'go เป็นกริยาไม่ปกติ ช่อง 2 คือ went ไม่มีคำว่า goed' },
  'My dog has a ball.': { tt:'สุนัขของฉันมีลูกบอล',
    en:'"My dog" is one animal (= it), so use "has", not "have".', th:'My dog เป็นเอกพจน์ (= it) จึงใช้ has ไม่ใช่ have' },
  'He will come tomorrow.': { tt:'เขาจะมาพรุ่งนี้',
    en:'After "will" use the base verb: come (no -s).', th:'หลัง will ใช้กริยาช่อง 1 ไม่เติม -s: come' },
  'I like ice cream.': { tt:'ฉันชอบไอศกรีม',
    en:'"like" is already a verb. Don\'t put "am" in front of it.', th:'like เป็นกริยาอยู่แล้ว ห้ามมี am นำหน้า' },
  'The zombie is sleeping now.': { tt:'ซอมบี้กำลังนอนหลับอยู่ตอนนี้',
    en:'Happening now = is / am / are + verb-ing: is sleeping. The sentence needs "is".', th:'กำลังเกิดขึ้นตอนนี้ = is / am / are + V-ing: is sleeping ประโยคจึงต้องมี is' },
  'Did you see the zombie?': { tt:'คุณเห็นซอมบี้ไหม?',
    en:'"Did" already shows the past, so the main verb stays in the base form: see, not saw.', th:'did บอกอดีตแล้ว กริยาหลักจึงใช้ช่อง 1: see ไม่ใช่ saw' },

  /* ---- 4 Adjectives ---- */
  'She has a red car.': { tt:'เธอมีรถสีแดง',
    en:'In English the adjective comes before the noun: red car.', th:'ภาษาอังกฤษวางคุณศัพท์ไว้หน้าคำนาม: red car (ภาษาไทยพูดว่า รถสีแดง)' },
  'She is very beautiful.': { tt:'เธอสวยมาก',
    en:'After "is very" we need an adjective: beautiful. "beauty" is a noun.', th:'หลัง is very ต้องใช้คุณศัพท์ beautiful ส่วน beauty เป็นคำนาม (ความสวย)' },
  'This test is easier than the last one.': { tt:'ข้อสอบนี้ง่ายกว่าครั้งที่แล้ว',
    en:'"easier" already means "more easy". Don\'t add "more".', th:'easier แปลว่า "ง่ายกว่า" อยู่แล้ว ห้ามใส่ more ซ้ำ' },
  'He is the tallest boy in class.': { tt:'เขาเป็นเด็กผู้ชายที่สูงที่สุดในห้อง',
    en:'"tallest" already means "most tall". Don\'t add "most".', th:'tallest แปลว่า "สูงที่สุด" อยู่แล้ว ห้ามใส่ most ซ้ำ' },
  'The zombie is very dangerous.': { tt:'ซอมบี้ตัวนี้อันตรายมาก',
    en:'After "is very" we need an adjective: dangerous. "danger" is a noun.', th:'หลัง is very ต้องใช้คุณศัพท์ dangerous ส่วน danger เป็นคำนาม (ภัยอันตราย)' },
  'It was a delicious meal.': { tt:'มันเป็นมื้ออาหารที่อร่อย',
    en:'Before the noun "meal" we need an adjective: delicious. "deliciously" is an adverb.', th:'หน้าคำนาม meal ต้องใช้คุณศัพท์ delicious ส่วน deliciously เป็นกริยาวิเศษณ์' },
  'Your English is better now.': { tt:'ภาษาอังกฤษของคุณดีขึ้นแล้ว',
    en:'"good" is special: good → better → best. "gooder" is not a word.', th:'good เปลี่ยนรูปพิเศษ: good → better → best ไม่มีคำว่า gooder' },
  'She has long black hair.': { tt:'เธอมีผมยาวสีดำ',
    en:'Size comes before color: long black hair.', th:'เรียงขนาดก่อนสี: long (ยาว) แล้วจึง black (ดำ)' },
  'I ate an apple.': { tt:'ฉันกินแอปเปิลไปหนึ่งผล',
    en:'"apple" starts with a vowel sound, so use "an", not "a".', th:'apple ขึ้นต้นด้วยเสียงสระ จึงใช้ an ไม่ใช่ a' },
  'He is a careful driver.': { tt:'เขาเป็นคนขับรถที่ระมัดระวัง',
    en:'Before the noun "driver" we need an adjective: careful. "carefully" is an adverb.', th:'หน้าคำนาม driver ต้องใช้คุณศัพท์ careful ส่วน carefully เป็นกริยาวิเศษณ์' },
  'The movie was boring.': { tt:'หนังเรื่องนั้นน่าเบื่อ',
    en:'The movie makes people bored, so it is "boring". "bored" is how a person feels.', th:'หนังเป็นสิ่งที่ทำให้คนเบื่อ จึงใช้ boring ส่วน bored ใช้กับคนที่รู้สึกเบื่อ' },
  'I feel tired today.': { tt:'วันนี้ฉันรู้สึกเหนื่อย',
    en:'This is how I feel, so use "tired" (-ed). "tiring" means something makes you tired.', th:'บอกความรู้สึกของเราใช้ tired (-ed) ส่วน tiring ใช้กับสิ่งที่ทำให้เหนื่อย' },

  /* ---- 5 Adverbs ---- */
  'She sings beautifully.': { tt:'เธอร้องเพลงไพเราะ',
    en:'The word tells HOW she sings, so we need the adverb with -ly: beautifully.', th:'คำนี้บอกว่าร้อง "อย่างไร" จึงต้องใช้กริยาวิเศษณ์ที่เติม -ly: beautifully' },
  'He drives carefully.': { tt:'เขาขับรถอย่างระมัดระวัง',
    en:'The word tells HOW he drives, so we need the adverb with -ly: carefully.', th:'คำนี้บอกว่าขับ "อย่างไร" จึงต้องใช้กริยาวิเศษณ์ที่เติม -ly: carefully' },
  'She speaks English very well.': { tt:'เธอพูดภาษาอังกฤษเก่งมาก',
    en:'To say HOW someone speaks, use the adverb "well". "good" is an adjective.', th:'บอกว่าพูด "อย่างไร" ต้องใช้กริยาวิเศษณ์ well ส่วน good เป็นคุณศัพท์' },
  'I always walk to school.': { tt:'ฉันเดินไปโรงเรียนเสมอ',
    en:'"always" goes before the main verb: always walk, not walk always.', th:'always ต้องวางหน้ากริยาแท้: always walk ไม่ใช่ walk always' },
  'They usually eat lunch at noon.': { tt:'พวกเขามักกินข้าวกลางวันตอนเที่ยง',
    en:'"usually" goes before the verb. It never sits between the verb and its object (eat … lunch).', th:'usually วางหน้ากริยา ห้ามแทรกระหว่างกริยากับกรรม (eat … lunch)' },
  'He answered the question correctly.': { tt:'เขาตอบคำถามได้ถูกต้อง',
    en:'The word tells HOW he answered, so use the adverb: correctly.', th:'คำนี้บอกว่าตอบ "อย่างไร" จึงต้องใช้กริยาวิเศษณ์ correctly' },
  'The cheetah runs very fast.': { tt:'เสือชีตาห์วิ่งเร็วมาก',
    en:'"fast" is both an adjective and an adverb. "fastly" is not a word.', th:'fast เป็นได้ทั้งคุณศัพท์และกริยาวิเศษณ์ ไม่มีคำว่า fastly' },
  'He works hard every day.': { tt:'เขาทำงานหนักทุกวัน',
    en:'"hard" is already an adverb. "hardly" means "almost not", so "He works hardly" means he almost doesn\'t work!', th:'hard เป็นกริยาวิเศษณ์อยู่แล้ว ส่วน hardly แปลว่า "แทบจะไม่" ถ้าพูด He works hardly จะกลายเป็น "เขาแทบไม่ทำงาน"' },
  'The test was extremely difficult.': { tt:'ข้อสอบยากมากจริง ๆ',
    en:'The word makes the adjective "difficult" stronger, so use the adverb: extremely.', th:'คำนี้ขยายคุณศัพท์ difficult ให้หนักขึ้น จึงต้องใช้กริยาวิเศษณ์ extremely' },
  'She quickly ran away.': { tt:'เธอรีบวิ่งหนีไป',
    en:'The word tells HOW she ran, so use the adverb: quickly.', th:'คำนี้บอกว่าวิ่ง "อย่างไร" จึงต้องใช้กริยาวิเศษณ์ quickly' },
  'I often play games.': { tt:'ฉันเล่นเกมบ่อย',
    en:'"often" goes before the verb, not between the verb and its object: often play games.', th:'often วางหน้ากริยา ห้ามแทรกระหว่างกริยากับกรรม: often play games' },
  'They arrived late again.': { tt:'พวกเขามาสายอีกแล้ว',
    en:'"late" is already an adverb. "lately" means "recently" — a different meaning.', th:'late (สาย) เป็นกริยาวิเศษณ์อยู่แล้ว ส่วน lately แปลว่า "ช่วงนี้" ความหมายคนละอย่าง' },
};
