/* =========================================================
   Answer key, lesson 2 · Tenses (see answers-1.js for the format)
   ========================================================= */
Object.assign(ANSWERS, {
  /* ---- T1 Present Simple ---- */
  'She goes to school by bus.': { tt:'เธอไปโรงเรียนโดยรถบัส',
    en:'She = he / she / it, so the present simple verb takes -es: go → goes.', th:'ประธาน She ต้องเติม -s / -es ที่กริยา: go → goes' },
  'The sun rises in the east.': { tt:'ดวงอาทิตย์ขึ้นทางทิศตะวันออก',
    en:'A fact that is always true → present simple. The sun = it, so rise → rises.', th:'ความจริงทั่วไป → Present Simple และ the sun = it กริยาต้องเติม -s: rise → rises' },
  'My father watches the news every night.': { tt:'พ่อของฉันดูข่าวทุกคืน',
    en:'"every night" = a habit. My father = he, and verbs ending in -ch add -es: watches.', th:'"every night" บอกนิสัย ประธาน my father = he และกริยาที่ลงท้ายด้วย -ch ต้องเติม -es: watches' },
  'They play football every Sunday.': { tt:'พวกเขาเล่นฟุตบอลทุกวันอาทิตย์',
    en:'They is plural, so the verb has no -s: they play.', th:'They เป็นพหูพจน์ กริยาไม่ต้องเติม -s: they play' },
  "He doesn't like coffee.": { tt:'เขาไม่ชอบกาแฟ',
    en:"He = he / she / it, so the \"not\" helper is doesn't, not don't.", th:"ประธาน He ต้องใช้ doesn't ไม่ใช่ don't" },
  'Does she speak English?': { tt:'เธอพูดภาษาอังกฤษได้ไหม?',
    en:'Questions with she use Does. The main verb stays in the base form: speak.', th:'คำถามที่ประธานเป็น she ใช้ Does และกริยาหลักใช้ช่อง 1: speak' },
  'I live in Chiang Mai.': { tt:'ฉันอาศัยอยู่ที่เชียงใหม่',
    en:"live is already the verb. Don't put am before an action verb in the present simple.", th:'live เป็นกริยาอยู่แล้ว ห้ามใส่ am หน้ากริยาใน Present Simple' },
  'Water boils at 100 degrees.': { tt:'น้ำเดือดที่ 100 องศา',
    en:'A science fact → present simple: water (it) boils. "is boil" mixes two forms.', th:'ข้อเท็จจริงทางวิทยาศาสตร์ → Present Simple: water (it) boils ส่วน "is boil" เอาสองรูปมาปนกัน' },
  'My brother studies every evening.': { tt:'พี่ชายของฉันอ่านหนังสือทุกเย็น',
    en:'study ends in consonant + y, so with he / she / it change y to -ies: studies.', th:'study ลงท้ายด้วยพยัญชนะ + y เมื่อประธานเป็น he / she / it ต้องเปลี่ยน y เป็น ies: studies' },
  "We don't eat meat.": { tt:'พวกเราไม่กินเนื้อสัตว์',
    en:"We takes don't. doesn't is only for he / she / it.", th:"We ใช้ don't ส่วน doesn't ใช้กับ he / she / it เท่านั้น" },

  /* ---- T2 Present Continuous ---- */
  'Look! The baby is sleeping.': { tt:'ดูสิ! เด็กทารกกำลังนอนหลับ',
    en:'"Look!" = right now → is + sleeping. "sleeping" alone is missing is.', th:'"Look!" = ตอนนี้ → ต้องใช้ is + sleeping ถ้ามีแค่ sleeping จะขาด is' },
  'I am reading a book right now.': { tt:'ตอนนี้ฉันกำลังอ่านหนังสือ',
    en:'am + verb-ing: am reading. After am the verb needs -ing.', th:'am + กริยาเติม -ing: am reading หลัง am กริยาต้องเติม -ing' },
  'They are playing games at the moment.': { tt:'ขณะนี้พวกเขากำลังเล่นเกม',
    en:'They takes are, not is: they are playing.', th:'They ใช้ are ไม่ใช่ is: they are playing' },
  'Listen! Someone is singing.': { tt:'ฟังสิ! มีคนกำลังร้องเพลง',
    en:'"Listen!" means it is happening now → is singing, not the present simple sings.', th:'"Listen!" แปลว่ากำลังเกิดขึ้นตอนนี้ → ใช้ is singing ไม่ใช่ sings' },
  'She is running in the park now.': { tt:'ตอนนี้เธอกำลังวิ่งอยู่ในสวน',
    en:'run ends in one vowel + one consonant, so double the n: running.', th:'run ลงท้ายด้วยสระเดียว + ตัวสะกดเดียว ต้องเพิ่ม n อีกตัว: running' },
  'We are making a cake.': { tt:'พวกเรากำลังทำเค้ก',
    en:'make ends in -e: drop the e, then add -ing → making.', th:'make ลงท้ายด้วย e ให้ตัด e แล้วเติม -ing: making' },
  'I know the answer.': { tt:'ฉันรู้คำตอบ',
    en:'know is a "knowing" verb, so it does not take -ing: I know, not I am knowing.', th:'know เป็นกริยาแสดงความรู้ ไม่ใช้รูป -ing: I know ไม่ใช่ I am knowing' },
  'He is not watching TV now.': { tt:'ตอนนี้เขาไม่ได้กำลังดูทีวี',
    en:'The negative keeps is: is not watching. "not watching" alone has no helper.', th:'ประโยคปฏิเสธต้องมี is: is not watching ถ้ามีแค่ not watching จะขาดตัวช่วย' },
  'Are you listening to me?': { tt:'คุณกำลังฟังฉันอยู่หรือเปล่า?',
    en:'A present continuous question starts with Are + you + -ing. Do does not go with -ing.', th:'คำถาม Present Continuous ขึ้นต้นด้วย Are + you + -ing ห้ามใช้ Do คู่กับ -ing' },
  'The children are swimming now.': { tt:'ตอนนี้เด็ก ๆ กำลังว่ายน้ำ',
    en:'swim: one vowel + one consonant → double the m: swimming.', th:'swim มีสระเดียว + ตัวสะกดเดียว ต้องเพิ่ม m อีกตัว: swimming' },

  /* ---- T3 Past Simple ---- */
  'I went to the beach yesterday.': { tt:'เมื่อวานฉันไปทะเล',
    en:'"yesterday" = finished past → verb 2: go → went.', th:'"yesterday" = อดีตที่จบแล้ว → ใช้กริยาช่อง 2: go → went' },
  'She visited her grandma last week.': { tt:'เธอไปเยี่ยมยายเมื่อสัปดาห์ที่แล้ว',
    en:'"last week" → past simple. visit is regular: add -ed → visited.', th:'"last week" → Past Simple และ visit เป็นกริยาปกติ เติม -ed: visited' },
  'We ate pizza last night.': { tt:'เมื่อคืนเรากินพิซซ่า',
    en:'eat is irregular: eat → ate. "eated" is not a word.', th:'eat เป็นกริยาผิดปกติ: eat → ate ไม่มีคำว่า eated' },
  "He didn't see the movie.": { tt:'เขาไม่ได้ดูหนังเรื่องนั้น',
    en:"After didn't the verb goes back to the base form: didn't see, not didn't saw.", th:"หลัง didn't กริยากลับเป็นช่อง 1: didn't see ไม่ใช่ didn't saw" },
  'Did you call me last night?': { tt:'เมื่อคืนคุณโทรหาฉันหรือเปล่า?',
    en:'"last night" is past, so the question uses Did, not Do.', th:'"last night" เป็นอดีต คำถามจึงใช้ Did ไม่ใช่ Do' },
  'They were at home last Sunday.': { tt:'วันอาทิตย์ที่แล้วพวกเขาอยู่บ้าน',
    en:'They takes were. was is for I / he / she / it.', th:'They ใช้ were ส่วน was ใช้กับ I / he / she / it' },
  'I bought a new phone two days ago.': { tt:'ฉันซื้อโทรศัพท์เครื่องใหม่เมื่อสองวันที่แล้ว',
    en:'buy is irregular: buy → bought. "buyed" is not a word.', th:'buy เป็นกริยาผิดปกติ: buy → bought ไม่มีคำว่า buyed' },
  'The train stopped suddenly.': { tt:'รถไฟหยุดกะทันหัน',
    en:'stop: one vowel + one consonant → double the p before -ed: stopped.', th:'stop มีสระเดียว + ตัวสะกดเดียว ต้องเพิ่ม p ก่อนเติม -ed: stopped' },
  'She was tired yesterday.': { tt:'เมื่อวานเธอเหนื่อย',
    en:'"yesterday" is past, so be changes too: is → was.', th:'"yesterday" เป็นอดีต กริยา be ก็ต้องเปลี่ยน: is → was' },
  'My dad taught me to swim.': { tt:'พ่อของฉันสอนฉันว่ายน้ำ',
    en:'teach is irregular: teach → taught. "teached" is not a word.', th:'teach เป็นกริยาผิดปกติ: teach → taught ไม่มีคำว่า teached' },

  /* ---- T4 Past Continuous ---- */
  'I was sleeping at 10 p.m. last night.': { tt:'เมื่อคืนตอนสี่ทุ่มฉันกำลังนอนหลับ',
    en:'In progress at a past time → was + verb-ing: was sleeping.', th:'กำลังทำอยู่ ณ เวลาหนึ่งในอดีต → was + กริยาเติม -ing: was sleeping' },
  'They were watching TV when I arrived.': { tt:'พวกเขากำลังดูทีวีอยู่ตอนที่ฉันมาถึง',
    en:'They takes were: they were watching.', th:'They ใช้ were: they were watching' },
  'She was cooking when the phone rang.': { tt:'เธอกำลังทำอาหารอยู่ตอนที่โทรศัพท์ดัง',
    en:'The long action needs both parts: was + cooking. The short action (rang) cut it.', th:'เรื่องที่ยาวต้องมีครบสองส่วน: was + cooking ส่วนเรื่องสั้น (rang) มาขัดจังหวะ' },
  "We were playing football at 5 o'clock yesterday.": { tt:'เมื่อวานตอนห้าโมงเย็นเรากำลังเล่นฟุตบอล',
    en:'"yesterday" is past, so are → were: were playing.', th:'"yesterday" เป็นอดีต ต้องเปลี่ยน are → were: were playing' },
  'While I was walking home, it started to rain.': { tt:'ขณะที่ฉันกำลังเดินกลับบ้าน ฝนก็เริ่มตก',
    en:'while + was / were + -ing. "I walking" has no helper.', th:'while + was / were + -ing ถ้าเป็น "I walking" จะขาดตัวช่วย' },
  'What were you doing last night?': { tt:'เมื่อคืนคุณกำลังทำอะไรอยู่?',
    en:'A past continuous question uses were + you + -ing. did does not go with -ing.', th:'คำถาม Past Continuous ใช้ were + you + -ing ห้ามใช้ did คู่กับ -ing' },
  "He wasn't listening to the teacher.": { tt:'เขาไม่ได้ฟังครูเลย',
    en:"The negative is wasn't + -ing. didn't does not go with -ing.", th:"ปฏิเสธใช้ wasn't + -ing ห้ามใช้ didn't คู่กับ -ing" },
  'I was having dinner when you called.': { tt:'ฉันกำลังกินข้าวเย็นอยู่ตอนที่คุณโทรมา',
    en:'After was the verb needs -ing: was having.', th:'หลัง was กริยาต้องเติม -ing: was having' },
  'When the teacher came in, the students were talking.': { tt:'ตอนที่ครูเดินเข้ามา นักเรียนกำลังคุยกันอยู่',
    en:'the students = they, so were, not was.', th:'the students = they จึงใช้ were ไม่ใช่ was' },
  'It was raining all morning.': { tt:'ฝนตกตลอดทั้งเช้า',
    en:'"all morning" = in progress for a long time → was raining, not was rain.', th:'"all morning" = กำลังเกิดอยู่ตลอดช่วงเวลา → was raining ไม่ใช่ was rain' },

  /* ---- T5 Present Perfect ---- */
  'I have finished my homework.': { tt:'ฉันทำการบ้านเสร็จแล้ว',
    en:'have + verb 3: have finished. "have finish" is missing -ed.', th:'have + กริยาช่อง 3: have finished ถ้าเป็น have finish จะขาด -ed' },
  'She has lived here for ten years.': { tt:'เธออาศัยอยู่ที่นี่มา 10 ปีแล้ว',
    en:'She = he / she / it → has, not have.', th:'ประธาน She ใช้ has ไม่ใช่ have' },
  'We have known each other since 2019.': { tt:'พวกเรารู้จักกันมาตั้งแต่ปี 2019',
    en:'"since 2019" = from the past until now → present perfect: have known.', th:'"since 2019" = ตั้งแต่อดีตจนถึงตอนนี้ → ใช้ Present Perfect: have known' },
  'Have you ever eaten durian?': { tt:'คุณเคยกินทุเรียนไหม?',
    en:'After have use verb 3: eat → ate → eaten.', th:'หลัง have ใช้กริยาช่อง 3: eat → ate → eaten' },
  'He has never been to Japan.': { tt:'เขาไม่เคยไปญี่ปุ่น',
    en:'has + verb 3: been. went is verb 2, so it cannot follow has.', th:'has + กริยาช่อง 3: been ส่วน went เป็นช่อง 2 ใช้หลัง has ไม่ได้' },
  'I saw him yesterday.': { tt:'ฉันเห็นเขาเมื่อวาน',
    en:'"yesterday" is a finished time, so use the past simple (saw), not the present perfect.', th:'"yesterday" เป็นเวลาที่จบแล้ว ต้องใช้ Past Simple (saw) ไม่ใช่ Present Perfect' },
  'They have just arrived.': { tt:'พวกเขาเพิ่งมาถึง',
    en:'have just + verb 3: arrived. "arrive" is missing -d.', th:'have just + กริยาช่อง 3: arrived ถ้าเป็น arrive จะขาด -d' },
  'Has she called you yet?': { tt:'เธอโทรหาคุณหรือยัง?',
    en:'She takes Has in a question, not Have.', th:'ประธาน she ใช้ Has ในคำถาม ไม่ใช่ Have' },
  'I have written three emails today.': { tt:'วันนี้ฉันเขียนอีเมลไปสามฉบับแล้ว',
    en:'write → wrote → written. After have use verb 3: written.', th:'write → wrote → written หลัง have ใช้กริยาช่อง 3: written' },
  'The movie has already started.': { tt:'หนังเริ่มไปแล้ว',
    en:'has already + verb 3: started.', th:'has already + กริยาช่อง 3: started' },

  /* ---- T6 Future ---- */
  'I will call you tomorrow.': { tt:'พรุ่งนี้ฉันจะโทรหาคุณ',
    en:'will + base verb: will call. Never will + -ing here.', th:'will + กริยาช่อง 1: will call ห้ามใช้ will + -ing' },
  'It is going to rain. Look at the clouds!': { tt:'ฝนกำลังจะตก ดูเมฆสิ!',
    en:'We can see it coming → is going to rain. going to needs is in front.', th:'เห็นแนวโน้มแล้ว → is going to rain และ going to ต้องมี is นำหน้า' },
  'She will be 15 next month.': { tt:'เดือนหน้าเธอจะอายุ 15 ปี',
    en:'After will use the base verb be, not is.', th:'หลัง will ใช้กริยาช่อง 1 คือ be ไม่ใช่ is' },
  'We are going to visit Chiang Mai next week.': { tt:'สัปดาห์หน้าเราจะไปเที่ยวเชียงใหม่',
    en:'going to + base verb: visit, not visited.', th:'going to + กริยาช่อง 1: visit ไม่ใช่ visited' },
  'Will you help me tomorrow?': { tt:'พรุ่งนี้คุณจะช่วยฉันไหม?',
    en:'"tomorrow" is the future, so the question starts with Will.', th:'"tomorrow" เป็นอนาคต คำถามจึงขึ้นต้นด้วย Will' },
  "He won't come to the party.": { tt:'เขาจะไม่มางานปาร์ตี้',
    en:"won't = will not, so the next verb is the base form: come, not comes.", th:"won't = will not กริยาที่ตามมาจึงเป็นช่อง 1: come ไม่ใช่ comes" },
  'I think it will be sunny tomorrow.': { tt:'ฉันคิดว่าพรุ่งนี้แดดจะออก',
    en:'A prediction about tomorrow needs will: will be. "it be" has no helper.', th:'การคาดเดาเรื่องพรุ่งนี้ต้องใช้ will: will be ถ้าเป็น "it be" จะขาดตัวช่วย' },
  'They are going to buy a new car.': { tt:'พวกเขาตั้งใจจะซื้อรถคันใหม่',
    en:'They takes are: they are going to.', th:'They ใช้ are: they are going to' },
  'I am going to study tonight.': { tt:'คืนนี้ฉันตั้งใจจะอ่านหนังสือ',
    en:'going to + base verb: study, not studying.', th:'going to + กริยาช่อง 1: study ไม่ใช่ studying' },
  'The shop will open at nine tomorrow.': { tt:'พรุ่งนี้ร้านจะเปิดตอนเก้าโมง',
    en:'"tomorrow" is the future, so opened (past) is wrong: will open.', th:'"tomorrow" เป็นอนาคต ใช้ opened (อดีต) ไม่ได้ ต้องเป็น will open' },

  /* ---- T7 Time Words ---- */
  'I have lived here for three years.': { tt:'ฉันอาศัยอยู่ที่นี่มา 3 ปีแล้ว',
    en:'"three years" is a length of time → for. since needs a starting point.', th:'"three years" เป็นระยะเวลา → ใช้ for ส่วน since ต้องตามด้วยจุดเริ่มต้น' },
  'She has worked here since 2020.': { tt:'เธอทำงานที่นี่ตั้งแต่ปี 2020',
    en:'2020 is a starting point → since. for needs a length of time.', th:'2020 เป็นจุดเริ่มต้น → ใช้ since ส่วน for ต้องตามด้วยระยะเวลา' },
  'I met him two days ago.': { tt:'ฉันเจอเขาเมื่อสองวันที่แล้ว',
    en:'ago comes after the time: two days ago.', th:'ago วางหลังระยะเวลา: two days ago' },
  "I haven't eaten yet.": { tt:'ฉันยังไม่ได้กินเลย',
    en:'In a "not" sentence use yet. already is for positive sentences.', th:'ประโยคปฏิเสธใช้ yet ส่วน already ใช้ในประโยคบอกเล่า' },
  'She has already left.': { tt:'เธอออกไปแล้ว',
    en:'A positive sentence takes already. yet is for questions and "not" sentences.', th:'ประโยคบอกเล่าใช้ already ส่วน yet ใช้ในคำถามและประโยคปฏิเสธ' },
  'I visited Chiang Mai last year.': { tt:'ฉันไปเที่ยวเชียงใหม่เมื่อปีที่แล้ว',
    en:'visited is past, so the time word must be past too: last year.', th:'visited เป็นอดีต คำบอกเวลาจึงต้องเป็นอดีตด้วย: last year' },
  'We will travel to Japan next month.': { tt:'เดือนหน้าเราจะไปเที่ยวญี่ปุ่น',
    en:'will travel is the future, so use next month, not last month.', th:'will travel เป็นอนาคต จึงใช้ next month ไม่ใช่ last month' },
  'Look! It is raining now.': { tt:'ดูสิ! ตอนนี้ฝนกำลังตก',
    en:'is raining = happening now, so the time word is now, not yesterday.', th:'is raining = กำลังเกิดขึ้น คำบอกเวลาจึงเป็น now ไม่ใช่ yesterday' },
  'I have never seen snow.': { tt:'ฉันไม่เคยเห็นหิมะ',
    en:'In a positive statement say never. ever is used in questions.', th:'ประโยคบอกเล่าใช้ never ส่วน ever ใช้ในคำถาม' },
  'It stopped raining an hour ago.': { tt:'ฝนหยุดตกเมื่อหนึ่งชั่วโมงที่แล้ว',
    en:'stopped is past simple, so use ago: an hour ago. since does not work here.', th:'stopped เป็น Past Simple จึงใช้ ago: an hour ago ใช้ since ไม่ได้' },

  /* ---- T8 Final: all tenses ---- */
  'He drinks milk every morning.': { tt:'เขาดื่มนมทุกเช้า',
    en:'"every morning" = a habit → present simple, and he → drinks.', th:'"every morning" = นิสัย → Present Simple และประธาน he ต้องเติม -s: drinks' },
  'Be quiet! The baby is sleeping.': { tt:'เงียบหน่อย! เด็กทารกกำลังนอนหลับ',
    en:'It is happening right now → is sleeping, not sleeps.', th:'กำลังเกิดขึ้นตอนนี้ → is sleeping ไม่ใช่ sleeps' },
  'We watched a movie last night.': { tt:'เมื่อคืนเราดูหนัง',
    en:'"last night" = finished past → watched.', th:'"last night" = อดีตที่จบแล้ว → watched' },
  'I was taking a shower when you called.': { tt:'ฉันกำลังอาบน้ำอยู่ตอนที่คุณโทรมา',
    en:'A long action cut by "when you called" → was taking (-ing).', th:'เรื่องยาวที่ถูกขัดด้วย "when you called" → was taking (เติม -ing)' },
  'She has worked here since 2018.': { tt:'เธอทำงานที่นี่ตั้งแต่ปี 2018',
    en:'"since 2018" = from then until now → present perfect: has worked.', th:'"since 2018" = ตั้งแต่ตอนนั้นจนถึงตอนนี้ → Present Perfect: has worked' },
  'I will help you tomorrow.': { tt:'พรุ่งนี้ฉันจะช่วยคุณ',
    en:'"tomorrow" = the future → will help, not helped.', th:'"tomorrow" = อนาคต → will help ไม่ใช่ helped' },
  'They went home two hours ago.': { tt:'พวกเขากลับบ้านไปเมื่อสองชั่วโมงที่แล้ว',
    en:'"ago" points to a finished time → past simple (went), not the present perfect.', th:'"ago" บอกเวลาที่จบแล้ว → Past Simple (went) ไม่ใช่ Present Perfect' },
  'Have you seen my keys?': { tt:'คุณเห็นกุญแจของฉันไหม?',
    en:'After have use verb 3: see → saw → seen.', th:'หลัง have ใช้กริยาช่อง 3: see → saw → seen' },
  'Look! It is snowing.': { tt:'ดูสิ! หิมะกำลังตก',
    en:'"Look!" = right now → is snowing.', th:'"Look!" = ตอนนี้ → is snowing' },
  'We are going to travel next summer.': { tt:'หน้าร้อนปีหน้าเราจะไปเที่ยว',
    en:'going to needs are in front: we are going to.', th:'going to ต้องมี are นำหน้า: we are going to' },
  "My sister doesn't eat fish.": { tt:'พี่สาวของฉันไม่กินปลา',
    en:"\"not\" in the present simple with she: doesn't + base verb. \"not eat\" has no helper.", th:"ปฏิเสธใน Present Simple ประธาน she ใช้ doesn't + กริยาช่อง 1 ถ้าเป็น not eat จะขาดตัวช่วย" },
  "I haven't finished it yet.": { tt:'ฉันยังทำมันไม่เสร็จ',
    en:'In a "not" sentence use yet, not already.', th:'ประโยคปฏิเสธใช้ yet ไม่ใช่ already' },
});
