/* =========================================================
   Answer key, levels 6–10 (see answers-1.js for the format)
   ========================================================= */
Object.assign(ANSWERS, {
  /* ---- 6 Prepositions ---- */
  'See you on Monday.': { tt:'เจอกันวันจันทร์',
    en:'Days of the week take "on": on Monday.', th:'วันในสัปดาห์ใช้ on: on Monday' },
  "The class starts at 8 o'clock.": { tt:'คาบเรียนเริ่มตอน 8 โมง',
    en:'Clock times take "at": at 8 o\'clock.', th:'เวลาบนนาฬิกาใช้ at: at 8 o\'clock' },
  'My birthday is in July.': { tt:'วันเกิดของฉันอยู่ในเดือนกรกฎาคม',
    en:'Months take "in": in July.', th:'เดือนใช้ in: in July' },
  'I was born in 2008.': { tt:'ฉันเกิดปี 2008',
    en:'Years take "in": in 2008.', th:'ปีใช้ in: in 2008' },
  'I am at home now.': { tt:'ตอนนี้ฉันอยู่บ้าน',
    en:'"at home" is a fixed phrase. We don\'t say "in home".', th:'at home เป็นวลีตายตัว ไม่พูดว่า in home' },
  'Please listen to the teacher.': { tt:'กรุณาฟังครู',
    en:'"listen" always goes with "to": listen to someone.', th:'listen ต้องตามด้วย to เสมอ: listen to + คนหรือสิ่งที่ฟัง' },
  'She is married to a doctor.': { tt:'เธอแต่งงานกับหมอ',
    en:'We say "married to" someone, not "married with".', th:'แต่งงานกับใคร ใช้ married to ไม่ใช่ married with' },
  'I am waiting for the bus.': { tt:'ฉันกำลังรอรถเมล์',
    en:'"wait" goes with "for": wait for the bus.', th:'wait ต้องตามด้วย for: wait for the bus' },
  'We go to school by bus.': { tt:'เราไปโรงเรียนโดยรถเมล์',
    en:'For transport, use "by": by bus, by car, by train.', th:'การเดินทางด้วยยานพาหนะใช้ by: by bus, by car, by train' },
  'She is afraid of zombies.': { tt:'เธอกลัวซอมบี้',
    en:'We say "afraid of" something.', th:'กลัวอะไร ใช้ afraid of' },
  'It depends on the weather.': { tt:'มันขึ้นอยู่กับสภาพอากาศ',
    en:'"depend" goes with "on": depend on.', th:'depend ต้องตามด้วย on: depend on' },
  'I have lived here since 2020.': { tt:'ฉันอาศัยอยู่ที่นี่ตั้งแต่ปี 2020',
    en:'A starting point in time takes "since": since 2020. "for" is for a length of time: for 5 years.', th:'จุดเริ่มต้นของเวลาใช้ since (since 2020) ส่วน for ใช้กับระยะเวลา (for 5 years)' },

  /* ---- 7 Conjunctions ---- */
  'Although it rained, we played outside.': { tt:'ถึงแม้ฝนจะตก เราก็ยังเล่นข้างนอก',
    en:'"Although" already joins the two ideas. Adding "but" makes two joining words.', th:'although เชื่อมสองประโยคแล้ว ถ้าเติม but จะมีคำเชื่อมซ้อนกันสองคำ' },
  'Because I was sick, I stayed home.': { tt:'เพราะฉันป่วย ฉันเลยอยู่บ้าน',
    en:'"Because" already joins the two ideas. Don\'t add "so" as well.', th:'because เชื่อมสองประโยคแล้ว ห้ามเติม so ซ้ำ' },
  'I like tea and coffee.': { tt:'ฉันชอบชาและกาแฟ',
    en:'You like both things, so add them with "and". "but" shows an opposite.', th:'ชอบทั้งสองอย่าง (เพิ่ม) จึงใช้ and ส่วน but ใช้กับเรื่องที่ขัดแย้งกัน' },
  'Do you want tea or coffee?': { tt:'คุณอยากได้ชาหรือกาแฟ?',
    en:'A choice between two things uses "or".', th:'ให้เลือกอย่างใดอย่างหนึ่ง ใช้ or' },
  'I was tired, so I went to bed.': { tt:'ฉันเหนื่อย จึงเข้านอน',
    en:'Going to bed is the result of being tired, so use "so".', th:'การเข้านอนเป็นผลของความเหนื่อย จึงใช้ so (จึง)' },
  'Both Tom and Anna are here.': { tt:'ทั้งทอมและแอนนาอยู่ที่นี่',
    en:'"both" always pairs with "and".', th:'both ต้องคู่กับ and เสมอ' },
  'You can either stay or go.': { tt:'คุณจะอยู่หรือไปก็ได้',
    en:'"either" always pairs with "or".', th:'either ต้องคู่กับ or เสมอ' },
  'Neither Tom nor Anna came.': { tt:'ทั้งทอมและแอนนาไม่มาเลย',
    en:'"neither" always pairs with "nor".', th:'neither ต้องคู่กับ nor เสมอ' },
  'She is poor but happy.': { tt:'เธอจนแต่มีความสุข',
    en:'Poor and happy don\'t usually go together, so we show the contrast with "but".', th:'ความจนกับความสุขขัดแย้งกัน จึงใช้ but (แต่)' },
  'Call me when you arrive.': { tt:'โทรหาฉันเมื่อคุณมาถึง',
    en:'This tells the time something happens, so use "when".', th:'บอกเวลาที่เหตุการณ์เกิดขึ้น จึงใช้ when (เมื่อ)' },
  'I will go if it stops raining.': { tt:'ฉันจะไปถ้าฝนหยุดตก',
    en:'This is a condition, so use "if".', th:'เป็นเงื่อนไข จึงใช้ if (ถ้า)' },
  'He ran fast, but he missed the bus.': { tt:'เขาวิ่งเร็วแล้ว แต่ก็ยังตกรถเมล์',
    en:'Running fast and still missing the bus is a contrast, so use "but". "so" would mean he missed it BECAUSE he ran fast.', th:'วิ่งเร็วแต่ยังตกรถเป็นเรื่องขัดแย้ง จึงใช้ but ถ้าใช้ so จะแปลว่าตกรถ "เพราะ" วิ่งเร็ว' },

  /* ---- 8 Interjections ---- */
  'Ouch! I hit my head.': { tt:'โอ๊ย! หัวฉันกระแทก',
    en:'Hitting your head hurts, so use "Ouch!" (pain). "Yum!" is for tasty food.', th:'หัวกระแทกคือความเจ็บ จึงใช้ Ouch! ส่วน Yum! ใช้กับอาหารอร่อย' },
  'Hooray! We won the game!': { tt:'ไชโย! เราชนะแล้ว!',
    en:'Winning is happy news, so use "Hooray!". "Ouch!" is for pain.', th:'ชนะคือข่าวดี จึงใช้ Hooray! ส่วน Ouch! ใช้ตอนเจ็บ' },
  'Yuck! This milk smells bad.': { tt:'แหวะ! นมนี้กลิ่นเหม็น',
    en:'Bad milk is disgusting, so use "Yuck!". "Yum!" means tasty.', th:'นมเหม็นน่าขยะแขยง จึงใช้ Yuck! ส่วน Yum! แปลว่าอร่อย' },
  'Yum! This cake is delicious.': { tt:'อร่อย! เค้กนี้อร่อยมาก',
    en:'Delicious cake gets "Yum!". "Yuck!" means disgusting.', th:'เค้กอร่อย จึงใช้ Yum! ส่วน Yuck! แปลว่าแหวะ' },
  'Oops! I dropped my phone.': { tt:'อุ๊ย! ฉันทำโทรศัพท์หล่น',
    en:'A small accident gets "Oops!". "Hooray!" is for good news.', th:'พลาดเล็กน้อย จึงใช้ Oops! ส่วน Hooray! ใช้กับข่าวดี' },
  'Shh! Be quiet in the library.': { tt:'ชู่ว์! เงียบ ๆ ในห้องสมุด',
    en:'Asking someone to be quiet uses "Shh!". "Hooray!" is a loud happy shout.', th:'ขอให้เงียบใช้ Shh! ส่วน Hooray! เป็นเสียงโห่ดีใจ' },
  'Phew! We escaped the zombies.': { tt:'เฮ้อ! เราหนีซอมบี้พ้นแล้ว',
    en:'Escaping danger brings relief, so use "Phew!". "Yuck!" means disgusting.', th:'หนีพ้นอันตรายคือความโล่งอก จึงใช้ Phew! ส่วน Yuck! แปลว่าแหวะ' },
  'Wow! What a beautiful view!': { tt:'ว้าว! วิวสวยมาก!',
    en:'A beautiful view is a happy surprise, so use "Wow!". "Ouch!" is for pain.', th:'วิวสวยทำให้ทึ่ง จึงใช้ Wow! ส่วน Ouch! ใช้ตอนเจ็บ' },
  'Oh no! I forgot my homework.': { tt:'แย่แล้ว! ฉันลืมการบ้าน',
    en:'Forgetting homework is bad news, so use "Oh no!". "Yum!" is for tasty food.', th:'ลืมการบ้านเป็นข่าวร้าย จึงใช้ Oh no! ส่วน Yum! ใช้กับอาหารอร่อย' },
  'Hey! Wait for me!': { tt:'เฮ้! รอฉันด้วย!',
    en:'Calling someone uses "Hey!". "Yuck!" means disgusting.', th:'เรียกให้คนหันมาใช้ Hey! ส่วน Yuck! แปลว่าแหวะ' },
  'Aha! I found the answer.': { tt:'อ๋อ! ฉันหาคำตอบเจอแล้ว',
    en:'Suddenly understanding something uses "Aha!". "Ouch!" is for pain.', th:'เพิ่งเข้าใจหรือค้นพบใช้ Aha! ส่วน Ouch! ใช้ตอนเจ็บ' },
  'Ugh! I have to wake up early.': { tt:'เซ็งจัง! ฉันต้องตื่นแต่เช้า',
    en:'Waking up early is annoying, so use "Ugh!". "Yum!" is for tasty food.', th:'ตื่นเช้าน่ารำคาญ จึงใช้ Ugh! ส่วน Yum! ใช้กับอาหารอร่อย' },

  /* ---- 9 Word forms ---- */
  'She made a good decision.': { tt:'เธอตัดสินใจได้ดี',
    en:'After "a good" we need a noun: decision. "decide" is a verb.', th:'หลัง a good ต้องเป็นคำนาม decision ส่วน decide เป็นกริยา' },
  'He is very successful.': { tt:'เขาประสบความสำเร็จมาก',
    en:'After "is very" we need an adjective: successful. "success" is a noun.', th:'หลัง is very ต้องใช้คุณศัพท์ successful ส่วน success เป็นคำนาม' },
  'I want to improve my English.': { tt:'ฉันอยากพัฒนาภาษาอังกฤษของฉัน',
    en:'After "to" we need a verb: improve. "improvement" is a noun.', th:'หลัง to ต้องใช้กริยา improve ส่วน improvement เป็นคำนาม' },
  'Education is very important.': { tt:'การศึกษาสำคัญมาก',
    en:'After "is very" we need an adjective: important. "importance" is a noun.', th:'หลัง is very ต้องใช้คุณศัพท์ important ส่วน importance เป็นคำนาม' },
  'Please drive safely.': { tt:'โปรดขับรถอย่างปลอดภัย',
    en:'The word tells HOW to drive, so use the adverb: safely. "safety" is a noun.', th:'คำนี้บอกว่าขับ "อย่างไร" ต้องใช้กริยาวิเศษณ์ safely ส่วน safety เป็นคำนาม' },
  'Thank you for your kindness.': { tt:'ขอบคุณสำหรับความใจดีของคุณ',
    en:'After "your" we need a noun: kindness. "kind" is an adjective.', th:'หลัง your ต้องเป็นคำนาม kindness ส่วน kind เป็นคุณศัพท์' },
  'The zombies destroyed the city.': { tt:'ซอมบี้ทำลายเมือง',
    en:'The sentence needs a verb to say what the zombies did: destroyed. "destruction" is a noun.', th:'ประโยคต้องมีกริยาบอกว่าซอมบี้ทำอะไร: destroyed ส่วน destruction เป็นคำนาม' },
  'She answered confidently.': { tt:'เธอตอบอย่างมั่นใจ',
    en:'The word tells HOW she answered, so use the adverb: confidently. "confidence" is a noun.', th:'คำนี้บอกว่าตอบ "อย่างไร" ต้องใช้กริยาวิเศษณ์ confidently ส่วน confidence เป็นคำนาม' },
  'This is a dangerous place.': { tt:'ที่นี่เป็นสถานที่อันตราย',
    en:'Before the noun "place" we need an adjective: dangerous. "danger" is a noun.', th:'หน้าคำนาม place ต้องใช้คุณศัพท์ dangerous ส่วน danger เป็นคำนาม' },
  'We need more information.': { tt:'เราต้องการข้อมูลเพิ่มเติม',
    en:'After "more" here we need a thing (a noun): information. "inform" is a verb.', th:'หลัง more ในที่นี้ต้องเป็นสิ่งของ (คำนาม) information ส่วน inform เป็นกริยา' },
  'Can you explain this word?': { tt:'คุณช่วยอธิบายคำนี้ได้ไหม?',
    en:'After "can" we need a verb: explain. "explanation" is a noun.', th:'หลัง can ต้องใช้กริยา explain ส่วน explanation เป็นคำนาม' },
  'The zombie moved silently.': { tt:'ซอมบี้เคลื่อนไหวอย่างเงียบ ๆ',
    en:'The word tells HOW it moved, so use the adverb: silently. "silence" is a noun.', th:'คำนี้บอกว่าเคลื่อนไหว "อย่างไร" ต้องใช้กริยาวิเศษณ์ silently ส่วน silence เป็นคำนาม' },

  /* ---- 10 Final boss (mixed) ---- */
  'They gave us free pizza.': { tt:'พวกเขาให้พิซซ่าฟรีกับพวกเรา',
    en:'Before the verb use "They"; after the verb "gave" use the object form "us".', th:'หน้ากริยาใช้ They ส่วนหลังกริยา gave ใช้รูปกรรม us' },
  'Two knives are on the table.': { tt:'มีดสองเล่มวางอยู่บนโต๊ะ',
    en:'"knife" changes -fe to -ves: knives. "knifes" is wrong.', th:'knife เปลี่ยน -fe เป็น -ves: knives ไม่ใช่ knifes' },
  'She studies English every day.': { tt:'เธอเรียนภาษาอังกฤษทุกวัน',
    en:'"She" in the present needs -s on the verb, and y changes to ies: study → studies.', th:'ประธาน she ในปัจจุบันต้องเติม -s และเปลี่ยน y เป็น ies: study → studies' },
  'It was a terrible day.': { tt:'มันเป็นวันที่แย่มาก',
    en:'Before the noun "day" we need an adjective: terrible. "terribly" is an adverb.', th:'หน้าคำนาม day ต้องใช้คุณศัพท์ terrible ส่วน terribly เป็นกริยาวิเศษณ์' },
  'She rarely eats meat.': { tt:'เธอแทบไม่กินเนื้อสัตว์',
    en:'"rarely" goes before the verb, not between the verb and its object (eats … meat).', th:'rarely วางหน้ากริยา ห้ามแทรกระหว่างกริยากับกรรม (eats … meat)' },
  'The party is on Friday.': { tt:'งานปาร์ตี้จัดวันศุกร์',
    en:'Days of the week take "on": on Friday.', th:'วันในสัปดาห์ใช้ on: on Friday' },
  'Although he is rich, he is not happy.': { tt:'ถึงแม้เขาจะรวย แต่เขาก็ไม่มีความสุข',
    en:'"Although" already joins the ideas, so don\'t add "but".', th:'ใช้ although แล้ว ห้ามมี but ซ้ำ' },
  'Wow! You look amazing.': { tt:'ว้าว! คุณดูดีมาก',
    en:'A nice surprise gets "Wow!". "Yuck!" means disgusting.', th:'ชมว่าดูดี จึงใช้ Wow! ส่วน Yuck! แปลว่าแหวะ' },
  'The zombie looks very hungry.': { tt:'ซอมบี้ดูหิวมาก',
    en:'After "looks very" we need an adjective: hungry. "hunger" is a noun.', th:'หลัง looks very ต้องใช้คุณศัพท์ hungry ส่วน hunger เป็นคำนาม (ความหิว)' },
  'I have two sisters.': { tt:'ฉันมีพี่สาวสองคน',
    en:'"I" goes with "have". "has" is for he / she / it.', th:'I ใช้คู่กับ have ส่วน has ใช้กับ he / she / it' },
  'We arrived at the station.': { tt:'เรามาถึงสถานีแล้ว',
    en:'We "arrive at" a place, not "arrive to".', th:'มาถึงสถานที่ใช้ arrive at ไม่ใช่ arrive to' },
  'I like this game because it is fun.': { tt:'ฉันชอบเกมนี้เพราะมันสนุก',
    en:'Being fun is the reason, so use "because". "although" shows an opposite.', th:'ความสนุกคือเหตุผล จึงใช้ because ส่วน although ใช้กับเรื่องที่ขัดแย้งกัน' },
  'Three sheep are eating grass.': { tt:'แกะสามตัวกำลังกินหญ้า',
    en:'"sheep" is the same for one and many: one sheep, three sheep.', th:'sheep รูปเอกพจน์และพหูพจน์เหมือนกัน: one sheep, three sheep' },
  'He speaks English fluently.': { tt:'เขาพูดภาษาอังกฤษได้คล่อง',
    en:'The word tells HOW he speaks, so use the adverb: fluently. "fluent" is an adjective.', th:'คำนี้บอกว่าพูด "อย่างไร" ต้องใช้กริยาวิเศษณ์ fluently ส่วน fluent เป็นคุณศัพท์' },
});
