/* =========================================================
   Grammar Virus — Parts of Speech edition
   - POS: the 8 parts of speech (name, Thai name, colour code)
   - STR: UI text in English (default) and Thai — plain text, icons live in the markup
   Level content lives in levels-1.js and levels-2.js
   ========================================================= */
const POS = {
  noun:         { en:'noun',         pl:'nouns',         th:'คำนาม',          color:'#5fa8ff' },
  pronoun:      { en:'pronoun',      pl:'pronouns',      th:'คำสรรพนาม',      color:'#b48cff' },
  verb:         { en:'verb',         pl:'verbs',         th:'คำกริยา',         color:'#ff7a59' },
  adjective:    { en:'adjective',    pl:'adjectives',    th:'คำคุณศัพท์',      color:'#3ddc97' },
  adverb:       { en:'adverb',       pl:'adverbs',       th:'คำกริยาวิเศษณ์',  color:'#ffb84d' },
  preposition:  { en:'preposition',  pl:'prepositions',  th:'คำบุพบท',         color:'#ffe066' },
  conjunction:  { en:'conjunction',  pl:'conjunctions',  th:'คำสันธาน',        color:'#ff8cc6' },
  interjection: { en:'interjection', pl:'interjections', th:'คำอุทาน',         color:'#4fd1ff' },
  // Unit 2: the tense of the highlighted verb (one = with its article, for "… is a past simple verb")
  presentSimple:  { en:'present simple',     pl:'present simple verbs',     one:'a present simple verb',     th:'ปัจจุบันธรรมดา',  color:'#5ab8ff' },
  presentCont:    { en:'present continuous', pl:'present continuous verbs', one:'a present continuous verb', th:'ปัจจุบันกำลังทำ', color:'#3fe0c5' },
  pastSimple:     { en:'past simple',        pl:'past simple verbs',        one:'a past simple verb',        th:'อดีตธรรมดา',     color:'#ff7f6a' },
  pastCont:       { en:'past continuous',    pl:'past continuous verbs',    one:'a past continuous verb',    th:'อดีตกำลังทำ',    color:'#ffa94d' },
  presentPerfect: { en:'present perfect',    pl:'present perfect verbs',    one:'a present perfect verb',    th:'ปัจจุบันสมบูรณ์', color:'#c58bff' },
  future:         { en:'future',             pl:'future verbs',             one:'a future verb',             th:'อนาคต',          color:'#9be15d' },
  timeWord:       { en:'time word',          pl:'time words',                                                th:'คำบอกเวลา',      color:'#ffd84d' },
};
const POS_ORDER = ['noun','pronoun','verb','adjective','adverb','preposition','conjunction','interjection'];
const TENSE_ORDER = ['presentSimple','presentCont','pastSimple','pastCont','presentPerfect','future','timeWord'];
const CAT_ORDER = POS_ORDER.concat(TENSE_ORDER);
// lessons: each level has unit 'pos' (Parts of Speech, the default) or 'tense'
const UNITS = [ { key:'pos', en:'Parts of Speech', th:'ชนิดของคำ' }, { key:'tense', en:'Tenses', th:'กาลของกริยา' } ];
// the job each part of speech does in a sentence (used to explain the boss sentence)
const POS_JOB = {
  noun:         { en:'names a person, place, thing or idea', th:'เรียกชื่อคน สถานที่ สิ่งของ หรือความคิด' },
  pronoun:      { en:'takes the place of a noun',            th:'ใช้แทนคำนาม' },
  verb:         { en:'shows an action or a state',           th:'บอกการกระทำหรือสภาพ' },
  adjective:    { en:'describes a noun',                     th:'ขยายคำนาม' },
  adverb:       { en:'describes a verb: how, when, how often', th:'ขยายกริยา: อย่างไร เมื่อไร บ่อยแค่ไหน' },
  preposition:  { en:'shows place or time before a noun',    th:'บอกสถานที่หรือเวลา วางหน้าคำนาม' },
  conjunction:  { en:'joins words or ideas',                 th:'เชื่อมคำหรือความคิด' },
  interjection: { en:'shows a sudden feeling',               th:'แสดงความรู้สึกฉับพลัน' },
  presentSimple:  { en:'habits and facts: every day, always',            th:'นิสัยและความจริงทั่วไป: ทุกวัน, เสมอ' },
  presentCont:    { en:'happening right now: am / is / are + -ing',      th:'กำลังเกิดขึ้นตอนนี้: am / is / are + -ing' },
  pastSimple:     { en:'finished in the past: verb 2',                   th:'จบไปแล้วในอดีต: กริยาช่อง 2' },
  pastCont:       { en:'in progress at a past time: was / were + -ing',  th:'กำลังทำอยู่ ณ เวลาหนึ่งในอดีต: was / were + -ing' },
  presentPerfect: { en:'from the past until now: have / has + verb 3',   th:'จากอดีตจนถึงตอนนี้: have / has + กริยาช่อง 3' },
  future:         { en:'later: will / be going to + verb',               th:'อนาคต: will / be going to + กริยา' },
  timeWord:       { en:'tells when, so it shows which tense to use',     th:'บอกเวลา จึงบอกว่าต้องใช้ tense ไหน' },
};

const STR = {
  en:{
    subtitle:'Grammar Zombie Shooter', menuKicker:'Outbreak alert · Parts of Speech & Tenses',
    tagline:'A virus is twisting English grammar: words turn into the wrong part of speech and verbs into the wrong tense. Kill the zombies that speak broken sentences and rescue the survivors who still speak correctly.',
    tabPlay:'Play', tabGuide:'Guide', tabNotebook:'Notebook', tabStats:'Stats', tabSettings:'Settings',
    playerLabel:'Player name', playerPh:'Player name (saved in playtest data)', howTo:'How to play',
    r1t:'Left click: kill', r1:'Highlighted word used wrongly? Fire the left rifle (kill round) at the broken sentence.',
    r2t:'Right click: rescue', r2:'Sentence correct? It is a survivor. Fire the right rifle (cure round) to save them.',
    r3t:'Wrong round hurts', r3:'Killing a survivor costs 15 HP. Curing a zombie costs 10 HP and makes it faster.',
    r4t:'Act before they reach you', r4:'Broken sentences bite for 10 HP. Survivors you don\'t rescue are lost.',
    r5t:'Boss: find the words', r5:'Bullets bounce off. Click every word of the part of speech it asks for.',
    r6t:'Power-ups & speaking', r6:'Combo ×5 heals 15 HP, SPACE = Slow-Mo. After the boss, read its sentence aloud for a bonus.',
    levels:'Campaign', level:'Level', starsTotal:'{0} / {1} stars',
    playLevel:'Play level {0}', review:'Review mistakes', reviewN:'Review mistakes ({0})',
    briefKicker:'Mission {0} · Briefing', whatIs:'What is it?', examples:'Examples', ruleLbl:'Rules to remember', clue:'How to spot it',
    watchOut:'Watch out',
    listen:'Listen', missionZ:'{0} zombies', missionBoss:'Boss: find the {0}', missionMixed:'Boss: find {0} kinds of words',
    start:'Start mission', back:'Back',
    hudLevel:'LV', hudScore:'Score', hudLeft:'Left', hudBoss:'Boss', hudCombo:'Combo ×{0}', hudReview:'Review',
    introKicker:'Mission {0}', go:'Left click: kill broken · Right click: rescue correct',
    gunKill:'Kill', gunKillSub:'broken sentence', gunCure:'Rescue', gunCureSub:'correct sentence',
    ctlKill:'Left click · kill broken', ctlCure:'Right click · rescue correct',
    bossIncoming:'BOSS INCOMING', bossHint:'Bullets bounce off. Find the words in the panel below.',
    bossBar:'Boss', bounce:'No effect. Use the word panel',
    meaning:'Meaning', findPrompt:'Find all the {0}', findLeft:'{0} left', stageOf:'Round {0} of {1}', stageClear:'All {0} found!',
    neutralHint:'"{0}" doesn\'t count in this round', wrongPos:'"{0}" is {1}', notPos:'"{0}" is not {1}',
    survivorHit:'That was a survivor! Right click rescues correct sentences.', rescued:'Survivor rescued',
    cureFail:'Cure failed! This sentence is broken. Left click kills it.', lost:'Survivor lost',
    healed:'Combo bonus +15 HP', slowReady:'Slow-Mo ready. Press SPACE', slowOn:'SLOW-MO',
    speakKicker:'Speaking bonus', speakTitle:'Say it out loud',
    speakDesc:'Press the microphone and read the boss sentence clearly. Listen first if you like.',
    speakBtn:'Speak', listening:'Listening… speak now', skip:'Skip', continue:'Continue',
    heard:'We heard: “{0}”', speakExcellent:'Excellent pronunciation! +{0}', speakGood:'Good try! +{0}',
    speakRetry:'Not quite. Try again!', noSpeech:'Speech recognition isn\'t supported in this browser (try Chrome or Edge). Read it aloud anyway.',
    micError:'Microphone problem: {0}',
    kWin:'Mission complete', kLose:'Mission failed', kReview:'Review complete',
    winTitle:'Level {0} cleared', winAll:'All levels cleared. You are a Grammar Ranger!', winAllTense:'All tense levels cleared. You are a Time Ranger!', winReview:'Notebook review done',
    loseTitle:'You were overrun',
    sScore:'Score', sAcc:'Accuracy', sDec:'Avg decision', sCombo:'Best combo', sSpeak:'Speaking', sMastered:'Mastered',
    secBitten:'Broken sentences that reached you', secSurvivor:'Survivors you shot (these were correct)',
    secFixed:'Broken sentences you killed', secBoss:'Boss sentence: parts of speech', tipTitle:'Remember',
    secWrongCure:'Broken sentences you tried to rescue', secLost:'Survivors you didn\'t rescue (these were correct)',
    secRescued:'Survivors you rescued', sRescued:'Rescued',
    whyLbl:'Why?', youSaw:'You saw this', bossJobs:'What each word does',
    hintReached:'These broken sentences reached you. Shoot them earlier with a kill round (left click).',
    hintWrongCure:'These sentences were broken, so the cure could not work. Use a kill round (left click).',
    hintSurvivor:'These sentences were already correct. Next time use a cure round (right click).',
    hintLost:'These correct sentences walked past you. Rescue them with a cure round (right click).',
    surveyTitle:'Quick playtest survey', surveyFun:'How fun was it?', surveyHard:'How difficult was it?',
    funLow:'Not fun', funHigh:'Very fun', easy:'Too easy', right:'Just right', hard:'Too hard', thanks:'Thanks for your feedback!',
    next:'Next level', replay:'Replay', retry:'Try again', menu:'Menu',
    guideTitle:'Parts of Speech guide', guideDesc:'Every word in a sentence has a job. These are the 8 parts of speech.',
    guideTitleTense:'Tenses guide', guideDescTense:'The verb tells WHEN something happens. These are the tenses in this game, and the time words that point to them.',
    unitLbl:'Lesson',
    guideForms:'Word-form clues',
    nbTitle:'Mistake notebook', nbDesc:'Every sentence you get wrong is saved here. Handle it correctly twice in a row to master it.',
    nbEmpty:'No mistakes yet. Go play!', nbNeed:'You need at least 3 sentences to start a review.',
    nbMisses:'Missed ×{0}', nbMastered:'{0} mastered', nbStart:'Start review', nbProgress:'Mastery',
    stTitle:'Progress & playtest data',
    stDesc:'Every game finished by every player is saved here. Pick a player to see only their data, or export everything for your playtest report.',
    stSessions:'Sessions', stAcc:'Accuracy', stStars:'Stars', stMastered:'Mastered', stNone:'Play a level to see your stats.',
    stPlayersN:'Players', stTime:'Play time', stLvCleared:'Levels cleared', stTotal:'Total score', stSvBest:'Survival best',
    stView:'Show data for', stAll:'All players', stNoName:'(no name)', stPick:'Click a player to see only their data. Click again to see everyone.',
    stByLevel:'Scores by level', stLevel:'Level', stPlayed:'Played', stCleared:'Cleared', stBest:'Best score', stAvg:'Average',
    stLast:'Last played',
    stExport:'Export CSV', stReset:'Reset progress', stConfirm:'Delete all progress, notebook and playtest logs?',
    setTitle:'Settings', setLang:'Language', setVoice:'Read sentences aloud', setSpeed:'Zombie speed',
    slow:'Relaxed', normal:'Normal', fast:'Hard', setSpeak:'Speaking bonus after boss', on:'On', off:'Off',
    paused:'Paused', resume:'Resume', quit:'Quit to menu', pauseTip:'Left click = kill · Right click or Shift+click = rescue · SPACE = Slow-Mo · Esc = pause',
    // survival mode + leaderboard
    tabBoard:'Leaderboard', svKicker:'Survival mode', svTitle:'All lessons mixed', svPlay:'Play Survival',
    svDesc:'All 8 parts of speech and every tense, mixed. The waves never stop and get faster until your HP runs out. Score as much as you can and climb the leaderboard.',
    svTop:'Players to beat', svNoRecord:'No records yet. Be the first!',
    svBriefKicker:'Survival mode · Briefing', svQ:'How long can you survive?', svRef:'Quick reference: what each part of speech and tense does',
    svRulesLbl:'Survival rules',
    svRule1:'Every lesson is mixed together: the 8 parts of speech, word forms and all the tenses.',
    svRule2:'The waves never end. Each new wave is faster and sends more zombies at once.',
    svRule3:'Every 3rd wave ends with a boss. Beat it to heal 20 HP.',
    svRule4:'Clear a wave for bonus points, doubled if you made no mistakes in it.',
    svRule5:'When your HP hits 0 the run is over and your score goes on the leaderboard.',
    svRule6:'Everyone plays at the same speed, so the leaderboard is fair.',
    svRuleHeal:'Every 3 correct answers heal 10% HP (instead of the combo heal).',
    svHealShort:'3 correct = +10% HP', svHealed:'3 correct · +10% HP',
    svName:'Your name for the leaderboard', svNeedName:'Type your name first so your score can go on the leaderboard.',
    svStart:'Start survival', svEndless:'Endless waves', svBossEvery:'Boss every 3 waves',
    svWave:'Wave {0}', svCleared:'Wave {0} cleared · +{1} bonus', svPerfect:'Perfect wave {0} · +{1} bonus',
    svFaster:'Faster zombies, more at once', svBossDown:'Boss defeated · +20 HP', svBossKicker:'Survival · Wave {0}',
    hudSurvival:'Survival', hudRecord:'Top {0} · {1}', hudNewRecord:'New record!',
    svEndRun:'End run & save score', svOverKicker:'Survival · Game over', svOverTitle:'You reached wave {0}',
    sWave:'Wave', sTime:'Survived',
    svNewRecord:'New #1 record! Everyone else is chasing you now.', svNewPB:'New personal best!',
    svPrevBest:'Your best is still {0}. Try again!', svNext:'Next player',
    bdTitle:'Survival leaderboard',
    bdDesc:'Every survival run is saved on this computer. The highest score ranks first; a tie goes to the higher wave, then the longer survival.',
    bdPlayers:'Players', bdRuns:'All runs', bdClear:'Clear leaderboard', bdConfirm:'Delete every run on the leaderboard?',
    bdEmpty:'No runs yet. Play Survival and set the first record!',
    bdRank:'Rank', bdPlayer:'Player', bdBest:'Best score', bdScore:'Score', bdWave:'Wave', bdTime:'Survived', bdAcc:'Accuracy',
    bdRunsN:'Runs', bdCombo:'Best combo', bdDate:'Date', bdYou:'You', bdBy:'by {0}', svOfPlayers:'of {0} players',
    bdKTop:'Top score', bdKWave:'Highest wave', bdKLong:'Longest survival', bdKPlayers:'Players', bdKRuns:'Runs played',
    // touch screens: "button" instead of "click" (TT() picks the …T text when the game is played by touch)
    r1tT:'Left button: kill', r2tT:'Right button: rescue', goT:'Left button: kill broken · Right button: rescue correct',
    ctlKillT:'Left button · kill broken', ctlCureT:'Right button · rescue correct',
    survivorHitT:'That was a survivor! The right button rescues correct sentences.',
    cureFailT:'Cure failed! This sentence is broken. The left button kills it.',
    hintReachedT:'These broken sentences reached you. Shoot them earlier with a kill round (left button).',
    hintWrongCureT:'These sentences were broken, so the cure could not work. Use a kill round (left button).',
    hintSurvivorT:'These sentences were already correct. Next time use a cure round (right button).',
    hintLostT:'These correct sentences walked past you. Rescue them with a cure round (right button).',
    pauseTipT:'Tap a zombie to target it (the closest one is targeted for you) · Left button = kill · Right button = rescue',
    tapHint:'Target locked. Press KILL or RESCUE',
    // pre-test / post-test
    qzPre:'Pre-test', qzPost:'Post-test', qzTestsLbl:'Tests', qzTitlePre:'What do you know already?', qzTitlePost:'How much did you learn?',
    qzDesc:'{0} sentences. Decide if each one is correct or wrong. There is no timer and no hint, so just answer what you think.',
    qzWhy:'Your score before and after playing shows how much the game helped you.', qzName:'Your name', qzNeedName:'Type your name first so your score is saved.',
    qzStart:'Start test', qzQ:'Question {0} of {1}', qzAsk:'Is this sentence correct?', qzRight:'Correct', qzWrong:'Wrong',
    qzDone:'Test finished', qzScore:'{0} / {1} correct', qzCompare:'Before playing {0}% → after playing {1}%',
    qzGainUp:'You improved by {0} points!', qzGainSame:'The same as before. Play the levels again, then retry.', qzGainDown:'{0} points lower. Review your notebook and try again.',
    qzPreNext:'Now play the lesson, then take the post-test to see how much you improved.', qzReview:'Check your mistakes', qzAllRight:'No mistakes at all. Excellent!',
    qzYouSaid:'You said: {0}', qzPlay:'Start the lesson', qzLast:'Last time: {0}%', qzNone:'not done',
    qzSuggest:'Before you start: take the 10-question pre-test so you can see how much you learn.',
    stTests:'Pre-test vs post-test', stTestsHint:"Each player's latest score in each lesson.", stLesson:'Lesson', stPre:'Before', stPost:'After', stGain:'Change',
    stAvgGain:'On average players improved by {0} points ({1} players did both tests).', stNoTests:'No tests yet. Start one from the Play tab.',
  },
  th:{
    subtitle:'เกมยิงซอมบี้ฝึกไวยากรณ์อังกฤษ', menuKicker:'แจ้งเตือนการระบาด · Parts of Speech & Tenses',
    tagline:'ไวรัสทำให้ไวยากรณ์เพี้ยน คำกลายเป็นชนิดที่ผิด กริยากลายเป็น tense ที่ผิด ยิงทำลายซอมบี้ที่พูดประโยคผิด และยิงยารักษาผู้รอดชีวิตที่ยังพูดถูกต้อง',
    tabPlay:'เล่น', tabGuide:'คู่มือ', tabNotebook:'สมุดคำผิด', tabStats:'สถิติ', tabSettings:'ตั้งค่า',
    playerLabel:'ชื่อผู้เล่น', playerPh:'ชื่อผู้เล่น (บันทึกในข้อมูล playtest)', howTo:'วิธีเล่น',
    r1t:'คลิกซ้าย: ยิงทำลาย', r1:'คำที่ไฮไลต์ใช้ผิด? ใช้ปืนซ้ายยิงกระสุนทำลายใส่ประโยคที่ผิด',
    r2t:'คลิกขวา: ยิงยารักษา', r2:'ประโยคถูก = ผู้รอดชีวิต ใช้ปืนขวายิงกระสุนยารักษาเพื่อช่วยเขา',
    r3t:'ใช้กระสุนผิดเจ็บตัว', r3:'ยิงผู้รอดชีวิต −15 HP ยิงยารักษาใส่ซอมบี้ −10 HP และมันจะเร็วขึ้น',
    r4t:'ตัดสินใจก่อนถึงตัว', r4:'ประโยคผิดที่ถึงตัวจะกัด −10 HP ผู้รอดชีวิตที่ไม่ได้รักษาจะหายไป',
    r5t:'บอส: หาคำให้ครบ', r5:'กระสุนทำอะไรบอสไม่ได้ ต้องคลิกทุกคำที่เป็นชนิดที่บอสถาม',
    r6t:'ไอเทมและการพูด', r6:'คอมโบ ×5 ฟื้นเลือด 15, SPACE = Slow-Mo และหลังชนะบอสอ่านประโยคออกเสียงเพื่อรับโบนัส',
    levels:'ด่านหลัก', level:'ด่าน', starsTotal:'{0} / {1} ดาว',
    playLevel:'เล่นด่าน {0}', review:'ทบทวนคำผิด', reviewN:'ทบทวนคำผิด ({0})',
    briefKicker:'ภารกิจ {0} · บรีฟ', whatIs:'คืออะไร?', examples:'ตัวอย่างคำ', ruleLbl:'กฎที่ต้องจำ', clue:'วิธีสังเกต',
    watchOut:'ระวัง! จุดที่คนไทยมักพลาด',
    listen:'ฟัง', missionZ:'ซอมบี้ {0} ตัว', missionBoss:'บอส: หา {0}', missionMixed:'บอส: หาคำ {0} ชนิด',
    start:'เริ่มภารกิจ', back:'กลับ',
    hudLevel:'ด่าน', hudScore:'คะแนน', hudLeft:'เหลือ', hudBoss:'บอส', hudCombo:'คอมโบ ×{0}', hudReview:'ทบทวน',
    introKicker:'ภารกิจ {0}', go:'คลิกซ้าย: ยิงประโยคผิด · คลิกขวา: รักษาประโยคถูก',
    gunKill:'ยิงทำลาย', gunKillSub:'ประโยคที่ผิด', gunCure:'ยิงรักษา', gunCureSub:'ประโยคที่ถูก',
    ctlKill:'คลิกซ้าย · ยิงประโยคผิด', ctlCure:'คลิกขวา · รักษาประโยคถูก',
    bossIncoming:'บอสกำลังมา', bossHint:'กระสุนไม่ระคายผิว หาคำในแผงด้านล่าง',
    bossBar:'บอส', bounce:'ไม่ได้ผล ใช้แผงคำด้านล่าง',
    meaning:'ความหมาย', findPrompt:'หา {0} ให้ครบ', findLeft:'เหลือ {0}', stageOf:'รอบ {0} จาก {1}', stageClear:'เจอ {0} ครบแล้ว!',
    neutralHint:'"{0}" ไม่นับในรอบนี้', wrongPos:'"{0}" เป็น {1}', notPos:'"{0}" ไม่ใช่ {1}',
    survivorHit:'นั่นคือผู้รอดชีวิต! ประโยคที่ถูกให้คลิกขวาเพื่อรักษา', rescued:'ช่วยผู้รอดชีวิตได้แล้ว',
    cureFail:'รักษาไม่ได้! ประโยคนี้ผิด ให้คลิกซ้ายยิงทำลาย', lost:'ผู้รอดชีวิตหายไป',
    healed:'คอมโบโบนัส +15 HP', slowReady:'Slow-Mo พร้อม กด SPACE', slowOn:'SLOW-MO',
    speakKicker:'โบนัสการพูด', speakTitle:'พูดออกเสียง',
    speakDesc:'กดไมโครโฟนแล้วอ่านประโยคของบอสให้ชัด จะกดฟังก่อนก็ได้',
    speakBtn:'พูด', listening:'กำลังฟัง… พูดได้เลย', skip:'ข้าม', continue:'ไปต่อ',
    heard:'ระบบได้ยินว่า: “{0}”', speakExcellent:'ออกเสียงยอดเยี่ยม! +{0}', speakGood:'ดีมาก! +{0}',
    speakRetry:'ยังไม่ค่อยตรง ลองอีกครั้ง', noSpeech:'เบราว์เซอร์นี้ไม่รองรับการฟังเสียง (ลอง Chrome หรือ Edge) แต่ลองอ่านออกเสียงดูนะ',
    micError:'ไมโครโฟนมีปัญหา: {0}',
    kWin:'ภารกิจสำเร็จ', kLose:'ภารกิจล้มเหลว', kReview:'ทบทวนเสร็จสิ้น',
    winTitle:'ผ่านด่าน {0} แล้ว', winAll:'ผ่านครบทุกด่าน คุณคือ Grammar Ranger!', winAllTense:'ผ่านบท Tenses ครบทุกด่าน คุณคือ Time Ranger!', winReview:'ทบทวนสมุดคำผิดเสร็จแล้ว',
    loseTitle:'คุณถูกซอมบี้รุมกิน',
    sScore:'คะแนน', sAcc:'ความแม่นยำ', sDec:'เวลาตัดสินใจเฉลี่ย', sCombo:'คอมโบสูงสุด', sSpeak:'การพูด', sMastered:'จำได้แล้ว',
    secBitten:'ประโยคผิดที่ปล่อยให้เข้ามากัด', secSurvivor:'ยิงผู้รอดชีวิต (ประโยคเหล่านี้ถูกอยู่แล้ว)',
    secFixed:'ประโยคผิดที่คุณยิงทำลาย', secBoss:'ประโยคของบอส: ชนิดของคำ', tipTitle:'จำไว้',
    secWrongCure:'ประโยคผิดที่คุณยิงยารักษาใส่', secLost:'ผู้รอดชีวิตที่ไม่ได้รักษา (ประโยคเหล่านี้ถูก)',
    secRescued:'ผู้รอดชีวิตที่คุณช่วยได้', sRescued:'ช่วยได้',
    whyLbl:'ทำไม?', youSaw:'คุณเห็นประโยคนี้', bossJobs:'แต่ละคำทำหน้าที่อะไร',
    hintReached:'ประโยคผิดเหล่านี้เดินมาถึงตัวคุณ ควรยิงกระสุนทำลาย (คลิกซ้าย) ให้เร็วขึ้น',
    hintWrongCure:'ประโยคเหล่านี้ผิด ยารักษาจึงใช้ไม่ได้ ควรใช้กระสุนทำลาย (คลิกซ้าย)',
    hintSurvivor:'ประโยคเหล่านี้ถูกอยู่แล้ว ครั้งหน้าใช้กระสุนยารักษา (คลิกขวา)',
    hintLost:'ประโยคถูกเหล่านี้เดินผ่านไปเฉย ๆ ควรใช้กระสุนยารักษา (คลิกขวา)',
    surveyTitle:'แบบสอบถามสั้น ๆ (playtest)', surveyFun:'สนุกแค่ไหน?', surveyHard:'ยากแค่ไหน?',
    funLow:'ไม่สนุก', funHigh:'สนุกมาก', easy:'ง่ายไป', right:'กำลังดี', hard:'ยากไป', thanks:'ขอบคุณสำหรับความคิดเห็น!',
    next:'ด่านถัดไป', replay:'เล่นอีกครั้ง', retry:'ลองใหม่', menu:'เมนู',
    guideTitle:'คู่มือชนิดของคำ', guideDesc:'ทุกคำในประโยคมีหน้าที่ของมัน นี่คือชนิดของคำทั้ง 8 ชนิด',
    guideTitleTense:'คู่มือ Tenses', guideDescTense:'กริยาบอกว่าเรื่องเกิดขึ้น "เมื่อไร" นี่คือ tense ทั้งหมดในเกมนี้ และคำบอกเวลาที่ช่วยบอกว่าต้องใช้ tense ไหน',
    unitLbl:'บทเรียน',
    guideForms:'สังเกตชนิดของคำจากคำลงท้าย',
    nbTitle:'สมุดจดคำผิด', nbDesc:'ประโยคที่คุณตอบผิดจะถูกเก็บไว้ที่นี่ ตอบถูก 2 ครั้งติดกันจึงจะนับว่าจำได้',
    nbEmpty:'ยังไม่มีคำผิด ไปเล่นกันเลย!', nbNeed:'ต้องมีอย่างน้อย 3 ประโยคจึงจะเริ่มทบทวนได้',
    nbMisses:'พลาด ×{0}', nbMastered:'จำได้แล้ว {0} ประโยค', nbStart:'เริ่มทบทวน', nbProgress:'ความจำ',
    stTitle:'ความก้าวหน้า & ข้อมูล playtest',
    stDesc:'ทุกเกมที่ผู้เล่นทุกคนเล่นจบจะถูกบันทึกไว้ที่นี่ เลือกผู้เล่นเพื่อดูเฉพาะข้อมูลของคนนั้น หรือส่งออกทั้งหมดไปใช้ในรายงาน playtest',
    stSessions:'จำนวนรอบ', stAcc:'ความแม่นยำ', stStars:'ดาว', stMastered:'จำได้แล้ว', stNone:'เล่นสักด่านเพื่อดูสถิติ',
    stPlayersN:'ผู้เล่น', stTime:'เวลาเล่นรวม', stLvCleared:'ด่านที่ผ่าน', stTotal:'คะแนนรวม', stSvBest:'สถิติเอาชีวิตรอด',
    stView:'ดูข้อมูลของ', stAll:'ผู้เล่นทุกคน', stNoName:'(ไม่ระบุชื่อ)', stPick:'คลิกที่ชื่อผู้เล่นเพื่อดูเฉพาะข้อมูลของคนนั้น คลิกซ้ำเพื่อกลับไปดูทุกคน',
    stByLevel:'คะแนนแต่ละด่าน', stLevel:'ด่าน', stPlayed:'เล่น (ครั้ง)', stCleared:'ผ่าน (ครั้ง)', stBest:'คะแนนสูงสุด', stAvg:'คะแนนเฉลี่ย',
    stLast:'เล่นล่าสุด',
    stExport:'ส่งออก CSV', stReset:'ล้างความคืบหน้า', stConfirm:'ลบความคืบหน้า สมุดคำผิด และข้อมูล playtest ทั้งหมด?',
    setTitle:'ตั้งค่า', setLang:'ภาษา', setVoice:'อ่านออกเสียงประโยค', setSpeed:'ความเร็วซอมบี้',
    slow:'ช้า', normal:'ปกติ', fast:'ยาก', setSpeak:'โบนัสการพูดหลังบอส', on:'เปิด', off:'ปิด',
    paused:'หยุดชั่วคราว', resume:'เล่นต่อ', quit:'กลับเมนู', pauseTip:'คลิกซ้าย = ยิงทำลาย · คลิกขวาหรือ Shift+คลิก = รักษา · SPACE = Slow-Mo · Esc = หยุดเกม',
    // โหมดเอาชีวิตรอด + ตารางอันดับ
    tabBoard:'อันดับ', svKicker:'โหมดเอาชีวิตรอด', svTitle:'รวมทุกบทเรียน', svPlay:'เล่นโหมดเอาชีวิตรอด',
    svDesc:'รวมคำทั้ง 8 ชนิดและ tense ทุกแบบไว้ด้วยกัน ซอมบี้มาเป็นระลอกไม่รู้จบและเร็วขึ้นเรื่อย ๆ จนกว่าเลือดจะหมด เก็บคะแนนให้ได้มากที่สุดแล้วไต่อันดับ',
    svTop:'ผู้เล่นที่ต้องเอาชนะ', svNoRecord:'ยังไม่มีสถิติ มาเป็นคนแรกเลย!',
    svBriefKicker:'โหมดเอาชีวิตรอด · บรีฟ', svQ:'คุณจะรอดได้นานแค่ไหน?', svRef:'สรุปย่อ: คำแต่ละชนิดและแต่ละ tense ทำหน้าที่อะไร',
    svRulesLbl:'กติกาโหมดเอาชีวิตรอด',
    svRule1:'รวมทุกบทเรียนไว้ด้วยกัน ทั้งชนิดของคำ 8 ชนิด การเปลี่ยนรูปคำ และ tense ทุกแบบ',
    svRule2:'ซอมบี้มาเป็นระลอกไม่มีวันจบ ระลอกใหม่จะเร็วขึ้นและมาพร้อมกันมากขึ้น',
    svRule3:'ทุก 3 ระลอกจะมีบอส ชนะบอสได้เลือดคืน 20 HP',
    svRule4:'ผ่านแต่ละระลอกได้คะแนนโบนัส ถ้าไม่พลาดเลยได้โบนัส 2 เท่า',
    svRule5:'เลือดหมดเมื่อไรจบเกมทันที คะแนนจะถูกบันทึกลงตารางอันดับ',
    svRule6:'ทุกคนเล่นด้วยความเร็วเท่ากัน ตารางอันดับจึงยุติธรรม',
    svRuleHeal:'ตอบถูกครบทุก 3 ข้อ ได้เลือดคืน 10% (ใช้แทนโบนัสคอมโบ)',
    svHealShort:'ถูก 3 ข้อ = +10% HP', svHealed:'ถูก 3 ข้อ · +10% HP',
    svName:'ชื่อของคุณในตารางอันดับ', svNeedName:'พิมพ์ชื่อก่อน เพื่อบันทึกคะแนนลงตารางอันดับ',
    svStart:'เริ่มเอาชีวิตรอด', svEndless:'ระลอกไม่รู้จบ', svBossEvery:'บอสทุก 3 ระลอก',
    svWave:'ระลอก {0}', svCleared:'ผ่านระลอก {0} · โบนัส +{1}', svPerfect:'ระลอก {0} ไม่พลาดเลย · โบนัส +{1}',
    svFaster:'ซอมบี้เร็วขึ้นและมาพร้อมกันมากขึ้น', svBossDown:'ชนะบอส · +20 HP', svBossKicker:'เอาชีวิตรอด · ระลอก {0}',
    hudSurvival:'เอาชีวิตรอด', hudRecord:'สถิติ {0} · {1}', hudNewRecord:'ทำลายสถิติแล้ว!',
    svEndRun:'จบรอบและบันทึกคะแนน', svOverKicker:'เอาชีวิตรอด · จบเกม', svOverTitle:'คุณไปถึงระลอก {0}',
    sWave:'ระลอก', sTime:'เวลาที่รอด',
    svNewRecord:'สถิติใหม่อันดับ 1! ตอนนี้ทุกคนต้องไล่ตามคุณ', svNewPB:'ทำคะแนนดีที่สุดของตัวเองได้ใหม่!',
    svPrevBest:'คะแนนดีที่สุดของคุณยังเป็น {0} ลองอีกครั้ง!', svNext:'ผู้เล่นคนถัดไป',
    bdTitle:'ตารางอันดับโหมดเอาชีวิตรอด',
    bdDesc:'ทุกรอบที่เล่นจะถูกบันทึกไว้ในเครื่องนี้ คะแนนสูงสุดได้อันดับแรก ถ้าคะแนนเท่ากันดูระลอกที่ไปถึง แล้วดูเวลาที่รอด',
    bdPlayers:'ผู้เล่น', bdRuns:'ทุกรอบ', bdClear:'ล้างตารางอันดับ', bdConfirm:'ลบทุกรอบในตารางอันดับ?',
    bdEmpty:'ยังไม่มีใครเล่น เล่นโหมดเอาชีวิตรอดแล้วสร้างสถิติแรกเลย!',
    bdRank:'อันดับ', bdPlayer:'ผู้เล่น', bdBest:'คะแนนสูงสุด', bdScore:'คะแนน', bdWave:'ระลอก', bdTime:'เวลาที่รอด', bdAcc:'ความแม่นยำ',
    bdRunsN:'จำนวนรอบ', bdCombo:'คอมโบสูงสุด', bdDate:'วันที่', bdYou:'คุณ', bdBy:'โดย {0}', svOfPlayers:'จาก {0} คน',
    bdKTop:'คะแนนสูงสุด', bdKWave:'ระลอกสูงสุด', bdKLong:'รอดนานที่สุด', bdKPlayers:'ผู้เล่น', bdKRuns:'จำนวนรอบที่เล่น',
    // จอสัมผัส: ใช้คำว่า "ปุ่ม" แทน "คลิก"
    r1tT:'ปุ่มซ้าย: ยิงทำลาย', r2tT:'ปุ่มขวา: ยิงยารักษา', goT:'ปุ่มซ้าย: ยิงประโยคผิด · ปุ่มขวา: รักษาประโยคถูก',
    ctlKillT:'ปุ่มซ้าย · ยิงประโยคผิด', ctlCureT:'ปุ่มขวา · รักษาประโยคถูก',
    survivorHitT:'นั่นคือผู้รอดชีวิต! ประโยคที่ถูกให้กดปุ่มขวาเพื่อรักษา',
    cureFailT:'รักษาไม่ได้! ประโยคนี้ผิด ให้กดปุ่มซ้ายยิงทำลาย',
    hintReachedT:'ประโยคผิดเหล่านี้เดินมาถึงตัวคุณ ควรยิงกระสุนทำลาย (ปุ่มซ้าย) ให้เร็วขึ้น',
    hintWrongCureT:'ประโยคเหล่านี้ผิด ยารักษาจึงใช้ไม่ได้ ควรใช้กระสุนทำลาย (ปุ่มซ้าย)',
    hintSurvivorT:'ประโยคเหล่านี้ถูกอยู่แล้ว ครั้งหน้าใช้กระสุนยารักษา (ปุ่มขวา)',
    hintLostT:'ประโยคถูกเหล่านี้เดินผ่านไปเฉย ๆ ควรใช้กระสุนยารักษา (ปุ่มขวา)',
    pauseTipT:'แตะซอมบี้เพื่อเล็ง (ถ้าไม่แตะ เกมจะเล็งตัวที่ใกล้ที่สุดให้) · ปุ่มซ้าย = ยิงทำลาย · ปุ่มขวา = รักษา',
    tapHint:'ล็อกเป้าแล้ว กดปุ่มยิงทำลายหรือยิงรักษา',
    // แบบทดสอบก่อน-หลังเรียน
    qzPre:'แบบทดสอบก่อนเรียน', qzPost:'แบบทดสอบหลังเรียน', qzTestsLbl:'แบบทดสอบ', qzTitlePre:'ตอนนี้รู้แค่ไหน?', qzTitlePost:'เรียนแล้วเก่งขึ้นแค่ไหน?',
    qzDesc:'มี {0} ข้อ ตัดสินว่าแต่ละประโยคถูกหรือผิด ไม่จับเวลาและไม่มีคำใบ้ ตอบตามที่คิดได้เลย',
    qzWhy:'คะแนนก่อนและหลังเล่นจะบอกว่าเกมช่วยให้คุณเก่งขึ้นแค่ไหน', qzName:'ชื่อของคุณ', qzNeedName:'พิมพ์ชื่อก่อน เพื่อบันทึกคะแนน',
    qzStart:'เริ่มทำแบบทดสอบ', qzQ:'ข้อ {0} จาก {1}', qzAsk:'ประโยคนี้ถูกหรือผิด?', qzRight:'ถูก', qzWrong:'ผิด',
    qzDone:'ทำแบบทดสอบเสร็จแล้ว', qzScore:'ตอบถูก {0} จาก {1} ข้อ', qzCompare:'ก่อนเล่น {0}% → หลังเล่น {1}%',
    qzGainUp:'เก่งขึ้น {0} คะแนน!', qzGainSame:'เท่าเดิม ลองเล่นด่านอีกรอบแล้วทำใหม่', qzGainDown:'ลดลง {0} คะแนน ลองทบทวนสมุดคำผิดแล้วทำใหม่',
    qzPreNext:'ต่อไปเล่นด่านในบทนี้ แล้วกลับมาทำแบบทดสอบหลังเรียน เพื่อดูว่าเก่งขึ้นแค่ไหน', qzReview:'เฉลยข้อที่ตอบผิด', qzAllRight:'ไม่ผิดเลยสักข้อ ยอดเยี่ยม!',
    qzYouSaid:'คุณตอบว่า: {0}', qzPlay:'เริ่มเล่นบทนี้', qzLast:'ครั้งล่าสุด: {0}%', qzNone:'ยังไม่ได้ทำ',
    qzSuggest:'ก่อนเริ่ม: ทำแบบทดสอบก่อนเรียน 10 ข้อ จะได้รู้ว่าเล่นแล้วเก่งขึ้นแค่ไหน',
    stTests:'แบบทดสอบก่อน-หลังเรียน', stTestsHint:'คะแนนล่าสุดของผู้เล่นแต่ละคนในแต่ละบท', stLesson:'บทเรียน', stPre:'ก่อนเรียน', stPost:'หลังเรียน', stGain:'เปลี่ยนแปลง',
    stAvgGain:'โดยเฉลี่ยผู้เล่นเก่งขึ้น {0} คะแนน (ทำครบทั้งสองชุด {1} คน)', stNoTests:'ยังไม่มีใครทำแบบทดสอบ เริ่มได้ที่หน้าเล่น',
  },
};
const LEVELS = [];   // filled by levels-1.js and levels-2.js

function T(key, ...args){
  const lang = (typeof Store!=='undefined' && Store.d && STR[Store.d.settings.lang]) ? Store.d.settings.lang : 'en';
  let s = STR[lang][key] ?? STR.en[key] ?? key;
  args.forEach((v,i)=>{ s = s.split('{'+i+'}').join(v); });
  return s;
}
// touch screens say "button" where the mouse version says "click": use the "…T" text when there is one
const isTouch = () => document.body.classList.contains('touch');
function TT(key, ...args){ return T(isTouch() && STR.en[key+'T'] ? key+'T' : key, ...args); }
// "adverb" in English mode, "คำกริยาวิเศษณ์ (adverb)" in Thai mode
function posName(p, plural=false){
  const m = POS[p]; if(!m) return p;
  const en = plural ? m.pl : m.en;
  return (typeof Store!=='undefined' && Store.d && Store.d.settings.lang==='th') ? `${m.th} (${en})` : en;
}
// with an English article: "an adverb", "a noun" (Thai needs none)
function posA(p){
  const m = POS[p];
  if(m && m.one && !(Store.d && Store.d.settings.lang==='th')) return m.one;     // "a past simple verb"
  const n = posName(p);
  return /^[a-z]/.test(n) ? (/^[aeiou]/.test(n) ? 'an ' : 'a ') + n : n;
}
