/* =========================================================
   Teaching text for each level (used by the briefing, the guide and the debrief)
   q        the question this part of speech answers
   def      one-sentence definition (en) + its Thai translation (th)
   groups   example words grouped by meaning; wordsTh = Thai meaning of each word, same order
   rules    one rule per line: en + th translation, a correct example (ok) + its Thai meaning (okTh),
            and a broken example (bad); [ ] = highlight
   clues    how to spot it: s → en (sTh / exTh = Thai meanings)
   tip      why Thai speakers often slip here
   Thai text is shown only in Thai mode; English mode stays English-only.
   ========================================================= */
const EXPLAIN = [
{ // 1 Nouns
  q:{ en:'Who? What?', th:'ใคร? อะไร?' },
  def:{ en:'A noun is a naming word. It names a person, a place, a thing or an idea.',
        th:'คำนามคือคำที่ใช้เรียกชื่อ เป็นชื่อของคน สถานที่ สิ่งของ หรือความคิด' },
  groups:[ { en:'person', th:'คน', words:'teacher · mother · Tom', wordsTh:'ครู · แม่ · ทอม' },
           { en:'place', th:'สถานที่', words:'school · Bangkok', wordsTh:'โรงเรียน · กรุงเทพฯ' },
           { en:'thing', th:'สิ่งของ', words:'phone · cat', wordsTh:'โทรศัพท์ · แมว' },
           { en:'idea', th:'ความคิด / ความรู้สึก', words:'happiness · love', wordsTh:'ความสุข · ความรัก' } ],
  rules:[ { en:'More than one? Add -s or -es.', th:'มีมากกว่าหนึ่ง ต้องเติม -s หรือ -es',
            ok:'two [cats] · five [boxes]', okTh:'แมว 2 ตัว · กล่อง 5 ใบ', bad:'two [cat]' },
          { en:'Some words change completely.', th:'บางคำเปลี่ยนทั้งคำ ไม่ได้เติม -s',
            ok:'child → [children] · mouse → [mice]', okTh:'เด็ก 1 คน → เด็กหลายคน · หนู 1 ตัว → หนูหลายตัว', bad:'three [childs]' },
          { en:'Some things can\'t be counted. No -s!', th:'คำนามที่นับไม่ได้ ห้ามเติม -s',
            ok:'[information] · [water] · [music]', okTh:'ข้อมูล · น้ำ · ดนตรี', bad:'[informations]' },
          { en:'Names of people and places start with a capital letter.', th:'ชื่อคนและชื่อสถานที่ ขึ้นต้นด้วยตัวพิมพ์ใหญ่',
            ok:'[Bangkok] · [Tom]', okTh:'กรุงเทพฯ · ทอม', bad:'[bangkok]' } ],
  clues:[ { s:'-tion', en:'information', exTh:'ข้อมูล' }, { s:'-ness', en:'happiness', exTh:'ความสุข' },
          { s:'-ment', en:'movement', exTh:'การเคลื่อนไหว' }, { s:'-er', en:'teacher', exTh:'ครู' }, { s:'-ity', en:'activity', exTh:'กิจกรรม' } ],
  clueNote:{ en:'Words that end like this are usually nouns.', th:'คำที่ลงท้ายแบบนี้ ส่วนใหญ่เป็นคำนาม' },
  tip:{ en:'Thai nouns never change for "more than one", so Thai speakers often forget the -s.',
        th:'ภาษาไทยไม่เปลี่ยนรูปคำนามตามจำนวน (แมว 1 ตัว, แมว 2 ตัว) คนไทยจึงมักลืมเติม -s' } },

{ // 2 Pronouns
  q:{ en:'Used instead of a noun', th:'ใช้แทนคำนาม' },
  def:{ en:'A pronoun takes the place of a noun, so we don\'t repeat it: Tom is tired → He is tired.',
        th:'คำสรรพนามใช้แทนคำนาม เพื่อจะได้ไม่ต้องพูดซ้ำ เช่น Tom is tired (ทอมเหนื่อย) → He is tired (เขาเหนื่อย)' },
  groups:[ { en:'before the verb', th:'หน้ากริยา (ผู้ทำ)', words:'I · he · she · we · they', wordsTh:'ฉัน · เขา · เธอ · เรา · พวกเขา' },
           { en:'after the verb', th:'หลังกริยา (ผู้ถูกกระทำ)', words:'me · him · her · us · them', wordsTh:'ฉัน · เขา · เธอ · เรา · พวกเขา' },
           { en:'owner, no noun after', th:'ของ... (ไม่มีคำนามตาม)', words:'mine · yours · hers · ours', wordsTh:'ของฉัน · ของคุณ · ของเธอ · ของเรา' },
           { en:'-self / -selves', th:'ตัวเอง', words:'myself · himself · ourselves', wordsTh:'ตัวฉันเอง · ตัวเขาเอง · ตัวเราเอง' } ],
  rules:[ { en:'Doing the action (before the verb): I, he, she, we, they.', th:'ผู้ทำ (อยู่หน้ากริยา) ใช้ I, he, she, we, they',
            ok:'[She] is my teacher.', okTh:'เธอเป็นครูของฉัน', bad:'[Her] is my teacher.' },
          { en:'Receiving the action (after a verb, or after to / with / for): me, him, her, us, them.', th:'ผู้ถูกกระทำ (หลังกริยา หรือหลัง to, with, for) ใช้ me, him, her, us, them',
            ok:'Tom likes [her]. · Give it to [them].', okTh:'ทอมชอบเธอ · เอามันให้พวกเขา', bad:'Tom likes [she].' },
          { en:'No noun after it? Use mine, yours, hers, ours.', th:'ถ้าไม่มีคำนามตามหลัง ใช้ mine, yours, hers, ours',
            ok:'This book is [mine].', okTh:'หนังสือเล่มนี้เป็นของฉัน', bad:'This book is [my].' },
          { en:'its = belongs to it. it\'s = it is.', th:'its = ของมัน ส่วน it\'s = it is (มันคือ / มันเป็น)',
            ok:'The cat licked [its] paw.', okTh:'แมวเลียอุ้งเท้าของมัน', bad:'[it\'s] paw' } ],
  clues:[ { s:'I', en:'me', exTh:'ฉัน' }, { s:'he', en:'him', exTh:'เขา' }, { s:'she', en:'her', exTh:'เธอ' },
          { s:'we', en:'us', exTh:'เรา' }, { s:'they', en:'them', exTh:'พวกเขา' } ],
  clueNote:{ en:'Learn them in pairs: before the verb → after the verb.', th:'จำเป็นคู่: หน้ากริยา → หลังกริยา (ความหมายเหมือนกัน แต่รูปต่างกัน)' },
  tip:{ en:'Thai uses the same word before and after the verb (เขา), but English changes it: he → him.',
        th:'ภาษาไทยใช้ "เขา" ได้ทั้งหน้าและหลังกริยา แต่ภาษาอังกฤษต้องเปลี่ยนรูป he → him' } },

{ // 3 Verbs
  q:{ en:'What happens?', th:'ทำอะไร? เกิดอะไรขึ้น?' },
  def:{ en:'A verb is an action word (run, eat, play) or a state word (be, have, like). Every sentence needs a verb.',
        th:'คำกริยาคือคำบอกการกระทำ เช่น run (วิ่ง), eat (กิน), play (เล่น) หรือบอกสภาพ เช่น be (เป็น / อยู่), have (มี), like (ชอบ) ทุกประโยคต้องมีกริยา' },
  groups:[ { en:'action', th:'การกระทำ', words:'run · eat · play · write', wordsTh:'วิ่ง · กิน · เล่น · เขียน' },
           { en:'state', th:'สภาพ / ความรู้สึก', words:'be · have · know · like', wordsTh:'เป็น / อยู่ · มี · รู้ · ชอบ' },
           { en:'helper', th:'กริยาช่วย', words:'do · does · can · will', wordsTh:'ทำ · ทำ · สามารถ · จะ' } ],
  rules:[ { en:'he / she / it in the present → add -s.', th:'ประธาน he / she / it (ปัจจุบัน) → กริยาเติม -s',
            ok:'She [goes] · He [plays]', okTh:'เธอไป · เขาเล่น', bad:'She [go]' },
          { en:'After can / will / must / did → the base verb only.', th:'หลัง can / will / must / did → ใช้กริยาช่อง 1 เปล่า ๆ',
            ok:'She can [swim]. · Did you [see] it?', okTh:'เธอว่ายน้ำได้ · คุณเห็นมันไหม?', bad:'She can [swims].' },
          { en:'Finished in the past → verb 2.', th:'เรื่องที่จบไปแล้วในอดีต → ใช้กริยาช่อง 2',
            ok:'go → [went] · eat → [ate]', okTh:'ไป → ไปแล้ว · กิน → กินแล้ว', bad:'Yesterday I [eat] rice.' },
          { en:'Never put am / is / are before another verb.', th:'ห้ามใช้ am / is / are นำหน้ากริยาตัวอื่น',
            ok:'I [agree]. · I [like] it.', okTh:'ฉันเห็นด้วย · ฉันชอบมัน', bad:'I [am] agree.' } ],
  clues:[ { s:'-ize', en:'realize', exTh:'ตระหนัก' }, { s:'-ify', en:'simplify', exTh:'ทำให้ง่ายขึ้น' },
          { s:'-ate', en:'create', exTh:'สร้าง' }, { s:'-en', en:'widen', exTh:'ทำให้กว้างขึ้น' } ],
  clueNote:{ en:'Words that end like this are often verbs.', th:'คำที่ลงท้ายแบบนี้ มักเป็นคำกริยา' },
  tip:{ en:'Thai verbs never change, but English verbs change with the subject and the time: go → goes → went.',
        th:'กริยาภาษาไทยไม่เปลี่ยนรูป แต่ภาษาอังกฤษเปลี่ยนตามประธานและเวลา: go → goes → went' } },

{ // 4 Adjectives
  q:{ en:'What kind? Which one?', th:'แบบไหน? เป็นอย่างไร?' },
  def:{ en:'An adjective describes a noun: its color, size, feeling or quality.',
        th:'คำคุณศัพท์ใช้บอกลักษณะของคำนาม เช่น สี ขนาด ความรู้สึก หรือคุณภาพ' },
  groups:[ { en:'color', th:'สี', words:'red · black', wordsTh:'แดง · ดำ' },
           { en:'size', th:'ขนาด', words:'big · tall · long', wordsTh:'ใหญ่ · สูง · ยาว' },
           { en:'feeling', th:'ความรู้สึก', words:'happy · tired · bored', wordsTh:'มีความสุข · เหนื่อย · เบื่อ' },
           { en:'quality', th:'ลักษณะ', words:'delicious · dangerous', wordsTh:'อร่อย · อันตราย' } ],
  rules:[ { en:'Put it BEFORE the noun.', th:'วางไว้ "หน้า" คำนาม (กลับกับภาษาไทย)',
            ok:'a [red car]', okTh:'รถสีแดง', bad:'a [car red]' },
          { en:'After is / look / feel, use the adjective, not the noun.', th:'หลัง is / look / feel ต้องใช้คุณศัพท์ ไม่ใช่คำนาม',
            ok:'She is very [beautiful].', okTh:'เธอสวยมาก', bad:'She is very [beauty].' },
          { en:'-ed = how you feel. -ing = the thing that makes you feel it.', th:'-ed = ความรู้สึกของเรา ส่วน -ing = สิ่งที่ทำให้เรารู้สึก',
            ok:'I feel [tired]. · The movie was [boring].', okTh:'ฉันรู้สึกเหนื่อย · หนังเรื่องนั้นน่าเบื่อ', bad:'The movie was [bored].' },
          { en:'Compare with -er / -est OR more / most, never both.', th:'เปรียบเทียบด้วย -er / -est หรือ more / most อย่างใดอย่างหนึ่ง',
            ok:'[easier] · the [tallest]', okTh:'ง่ายกว่า · สูงที่สุด', bad:'[more] easier' },
          { en:'a before a consonant sound, an before a vowel sound.', th:'a ใช้หน้าเสียงพยัญชนะ ส่วน an ใช้หน้าเสียงสระ',
            ok:'[an] apple · [a] cat', okTh:'แอปเปิลหนึ่งผล · แมวหนึ่งตัว', bad:'[a] apple' } ],
  clues:[ { s:'-ful', en:'careful', exTh:'ระมัดระวัง' }, { s:'-ous', en:'dangerous', exTh:'อันตราย' },
          { s:'-ive', en:'active', exTh:'กระฉับกระเฉง' }, { s:'-able', en:'comfortable', exTh:'สบาย' }, { s:'-y', en:'hungry', exTh:'หิว' } ],
  clueNote:{ en:'Words that end like this are usually adjectives.', th:'คำที่ลงท้ายแบบนี้ ส่วนใหญ่เป็นคำคุณศัพท์' },
  tip:{ en:'Thai puts the describing word after the noun (รถสีแดง = car red). English puts it before: red car.',
        th:'ภาษาไทยพูดว่า "รถสีแดง" (นาม + คุณศัพท์) แต่ภาษาอังกฤษเรียงกลับเป็น "red car"' } },

{ // 5 Adverbs
  q:{ en:'How? When? How often?', th:'อย่างไร? เมื่อไร? บ่อยแค่ไหน?' },
  def:{ en:'An adverb tells us more about a verb: how, when or how often something happens. Words like very and really are adverbs too.',
        th:'คำกริยาวิเศษณ์บอกรายละเอียดของกริยา ว่าเกิดขึ้น "อย่างไร เมื่อไร บ่อยแค่ไหน" คำอย่าง very (มาก) และ really (จริง ๆ) ก็เป็นกริยาวิเศษณ์' },
  groups:[ { en:'how', th:'อย่างไร', words:'quickly · carefully · well', wordsTh:'อย่างรวดเร็ว · อย่างระมัดระวัง · ดี / เก่ง' },
           { en:'when', th:'เมื่อไร', words:'yesterday · late · now', wordsTh:'เมื่อวาน · สาย · ตอนนี้' },
           { en:'how often', th:'บ่อยแค่ไหน', words:'always · often · never', wordsTh:'เสมอ · บ่อย · ไม่เคย' },
           { en:'how much', th:'มากแค่ไหน', words:'very · really · extremely', wordsTh:'มาก · จริง ๆ · อย่างยิ่ง' } ],
  rules:[ { en:'Adjective + -ly = adverb.', th:'คุณศัพท์ + -ly = กริยาวิเศษณ์',
            ok:'quick → [quickly] · careful → [carefully]', okTh:'เร็ว → อย่างรวดเร็ว · ระวัง → อย่างระมัดระวัง', bad:'She sings [beautiful].' },
          { en:'Special words: good → well. fast and hard stay the same.', th:'คำพิเศษ: good → well ส่วน fast กับ hard ใช้รูปเดิม',
            ok:'She speaks very [well]. · He runs [fast].', okTh:'เธอพูดเก่งมาก · เขาวิ่งเร็ว', bad:'He runs [fastly].' },
          { en:'always / often / never go before the main verb.', th:'always / often / never วางไว้หน้ากริยาแท้',
            ok:'I [always] walk to school.', okTh:'ฉันเดินไปโรงเรียนเสมอ', bad:'I walk [always] to school.' },
          { en:'Careful: hardly = almost not, lately = recently.', th:'ระวัง: hardly = แทบจะไม่ ส่วน lately = ช่วงนี้ (ความหมายเปลี่ยน!)',
            ok:'He works [hard].', okTh:'เขาทำงานหนัก', bad:'He works [hardly].' } ],
  clues:[ { s:'-ly', en:'slowly', exTh:'อย่างช้า ๆ' }, { s:'how?', sTh:'อย่างไร', en:'well', exTh:'ดี' },
          { s:'when?', sTh:'เมื่อไร', en:'yesterday', exTh:'เมื่อวาน' }, { s:'how often?', sTh:'บ่อยแค่ไหน', en:'always', exTh:'เสมอ' } ],
  clueNote:{ en:'Most -ly words are adverbs. Ask: does it tell how, when or how often?', th:'คำที่ลงท้าย -ly ส่วนใหญ่เป็นกริยาวิเศษณ์ ลองถามว่ามันบอก "อย่างไร / เมื่อไร / บ่อยแค่ไหน" หรือไม่' },
  tip:{ en:'Thai uses one word for both jobs, but English needs two: beautiful (adjective) and beautifully (adverb).',
        th:'ภาษาไทยใช้ "เพราะ" ได้ทั้ง "เพลงเพราะ" และ "ร้องเพราะ" แต่อังกฤษต้องแยก beautiful (คุณศัพท์) กับ beautifully (กริยาวิเศษณ์)' } },

{ // 6 Prepositions
  q:{ en:'Where? When?', th:'ที่ไหน? เมื่อไร?' },
  def:{ en:'A preposition is a small word before a noun. It shows place, time or direction.',
        th:'คำบุพบทเป็นคำเล็ก ๆ ที่วางหน้าคำนาม เพื่อบอกสถานที่ เวลา หรือทิศทาง' },
  groups:[ { en:'place', th:'สถานที่', words:'in · on · at · under', wordsTh:'ใน · บน · ที่ · ใต้' },
           { en:'time', th:'เวลา', words:'at · on · in · since', wordsTh:'ตอน (เวลา) · ใน (วัน) · ใน (เดือน / ปี) · ตั้งแต่' },
           { en:'direction', th:'ทิศทาง', words:'to · from · into', wordsTh:'ไปยัง · จาก · เข้าไปใน' },
           { en:'how', th:'วิธีการ', words:'by bus · with a pen', wordsTh:'โดยรถเมล์ · ด้วยปากกา' } ],
  rules:[ { en:'AT + a clock time.', th:'at + เวลาบนนาฬิกา',
            ok:'[at] 8 o\'clock · [at] night', okTh:'ตอน 8 โมง · ตอนกลางคืน', bad:'[on] 8 o\'clock' },
          { en:'ON + a day or a date.', th:'on + วัน หรือวันที่',
            ok:'[on] Monday · [on] 5 May', okTh:'วันจันทร์ · วันที่ 5 พฤษภาคม', bad:'[in] Monday' },
          { en:'IN + a month, a year or a season.', th:'in + เดือน ปี หรือฤดู',
            ok:'[in] July · [in] 2008', okTh:'ในเดือนกรกฎาคม · ในปี 2008', bad:'[at] July' },
          { en:'Some words always take the same partner.', th:'บางคำต้องใช้คู่กับบุพบทตัวเดิมเสมอ',
            ok:'listen [to] · wait [for] · afraid [of] · married [to]', okTh:'ฟัง · รอ · กลัว · แต่งงานกับ', bad:'married [with]' } ],
  clues:[ { s:'at', en:'8 o\'clock', exTh:'8 โมง' }, { s:'on', en:'Monday', exTh:'วันจันทร์' },
          { s:'in', en:'July', exTh:'กรกฎาคม' }, { s:'by', en:'bus', exTh:'รถเมล์' } ],
  clueNote:{ en:'Small → big: at (a time) → on (a day) → in (a month or a year).', th:'จากเล็กไปใหญ่: at (เวลา) → on (วัน) → in (เดือน / ปี)' },
  tip:{ en:'Thai can use one word for many times (ตอน, ใน), but English must pick in, on or at exactly.',
        th:'ภาษาไทยใช้ "ใน / ตอน" กับเวลาได้หลายแบบ แต่ภาษาอังกฤษต้องเลือก in / on / at ให้ตรง' } },

{ // 7 Conjunctions
  q:{ en:'How are the ideas linked?', th:'สองความคิดเชื่อมกันแบบไหน?' },
  def:{ en:'A conjunction joins words or sentences: and, but, or, so, because.',
        th:'คำสันธานใช้เชื่อมคำหรือประโยคเข้าด้วยกัน เช่น and (และ), but (แต่), or (หรือ), so (จึง), because (เพราะ)' },
  groups:[ { en:'add', th:'เพิ่ม', words:'and', wordsTh:'และ' },
           { en:'opposite', th:'ขัดแย้ง', words:'but · although', wordsTh:'แต่ · ถึงแม้ว่า' },
           { en:'choice', th:'ตัวเลือก', words:'or', wordsTh:'หรือ' },
           { en:'reason / result', th:'เหตุ / ผล', words:'because · so', wordsTh:'เพราะ · จึง / ดังนั้น' },
           { en:'time / condition', th:'เวลา / เงื่อนไข', words:'when · if', wordsTh:'เมื่อ · ถ้า' } ],
  rules:[ { en:'Choose by meaning: and (add), but (opposite), or (choice), so (result), because (reason).', th:'เลือกให้ตรงความหมาย: and = และ, but = แต่, or = หรือ, so = จึง, because = เพราะ',
            ok:'I was tired, [so] I went to bed.', okTh:'ฉันเหนื่อย จึงเข้านอน', bad:'I like tea [but] coffee.' },
          { en:'although → no but.', th:'ใช้ although แล้ว ห้ามมี but',
            ok:'[Although] it rained, we played.', okTh:'ถึงแม้ฝนจะตก เราก็ยังเล่น', bad:'Although it rained, [but] we played.' },
          { en:'because → no so.', th:'ใช้ because แล้ว ห้ามมี so',
            ok:'[Because] I was sick, I stayed home.', okTh:'เพราะฉันป่วย ฉันเลยอยู่บ้าน', bad:'Because I was sick, [so] I stayed home.' },
          { en:'Some pairs stay together: both … and, either … or, neither … nor.', th:'คู่ที่ต้องใช้ด้วยกัน: both … and (ทั้ง…และ), either … or (…หรือ…), neither … nor (ไม่ทั้ง…และ)',
            ok:'[Both] Tom [and] Anna', okTh:'ทั้งทอมและแอนนา', bad:'Both Tom [or] Anna' } ],
  clues:[ { s:'and', en:'add', exTh:'และ' }, { s:'but', en:'opposite', exTh:'แต่' }, { s:'or', en:'choice', exTh:'หรือ' },
          { s:'so', en:'result', exTh:'จึง' }, { s:'because', en:'reason', exTh:'เพราะ' } ],
  clueNote:{ en:'Ask yourself: how are the two ideas connected?', th:'ถามตัวเองว่า สองความคิดนี้เกี่ยวกันแบบไหน' },
  tip:{ en:'Thai says "although … but …" and "because … so …". English uses only one word from each pair.',
        th:'ภาษาไทยพูดว่า "ถึงแม้...แต่..." และ "เพราะ...จึง..." ได้ แต่ภาษาอังกฤษใช้คำเชื่อมแค่คำเดียว' } },

{ // 8 Interjections
  q:{ en:'How do you feel?', th:'รู้สึกอย่างไร?' },
  def:{ en:'An interjection is a short word that shows a sudden feeling. It usually comes first, with ! after it.',
        th:'คำอุทานเป็นคำสั้น ๆ ที่แสดงความรู้สึกทันที มักอยู่ต้นประโยคและตามด้วยเครื่องหมาย !' },
  groups:[ { en:'good news', th:'เรื่องดี', words:'Wow! · Hooray! · Yum! · Phew!', wordsTh:'ว้าว · ไชโย · อร่อย · เฮ้อ (โล่งอก)' },
           { en:'bad news', th:'เรื่องไม่ดี', words:'Ouch! · Oops! · Yuck! · Oh no!', wordsTh:'โอ๊ย · อุ๊ย · แหวะ · แย่แล้ว' },
           { en:'calling / quiet', th:'เรียก / ให้เงียบ', words:'Hey! · Shh!', wordsTh:'เฮ้ · ชู่ว์' } ],
  rules:[ { en:'Match the word to the feeling.', th:'เลือกคำอุทานให้ตรงกับความรู้สึก',
            ok:'[Ouch!] I hit my head.', okTh:'โอ๊ย! หัวฉันกระแทก', bad:'[Yum!] I hit my head.' },
          { en:'Read the whole sentence first: good news or bad news?', th:'อ่านทั้งประโยคก่อน ว่าเป็นเรื่องดีหรือเรื่องไม่ดี',
            ok:'[Hooray!] We won the game!', okTh:'ไชโย! เราชนะแล้ว!', bad:'[Ouch!] We won the game!' },
          { en:'Put ! or a comma after it.', th:'ตามด้วย ! หรือเครื่องหมาย ,',
            ok:'[Wow!] What a view! · [Oops,] I forgot.', okTh:'ว้าว! วิวสวยจัง · อุ๊ย ฉันลืม' } ],
  clues:[ { s:'Ouch', en:'pain', exTh:'โอ๊ย / เจ็บ' }, { s:'Oops', en:'small mistake', exTh:'อุ๊ย / พลาด' }, { s:'Yuck', en:'disgusting', exTh:'แหวะ' },
          { s:'Phew', en:'relief', exTh:'เฮ้อ / โล่งอก' }, { s:'Aha', en:'I found it!', exTh:'อ๋อ / เข้าใจแล้ว' } ],
  clueNote:{ en:'Each interjection belongs to one feeling. Learn them in pairs.', th:'คำอุทานแต่ละคำคู่กับความรู้สึกหนึ่งแบบ จำเป็นคู่ ๆ' },
  tip:{ en:'They work like sound effects: Ouch for pain, Oops for small mistakes, Yuck for bad tastes.',
        th:'เทียบกับคำไทยได้เลย: Ouch = โอ๊ย, Oops = อุ๊ย, Yuck = แหวะ, Wow = ว้าว' } },

{ // 9 Word forms
  q:{ en:'Which form fits the gap?', th:'ช่องนี้ต้องใช้รูปไหน?' },
  def:{ en:'One word family can be a noun, a verb, an adjective or an adverb. Choose the form that fits its place in the sentence.',
        th:'คำตระกูลเดียวกันเปลี่ยนรูปได้เป็นคำนาม กริยา คุณศัพท์ หรือกริยาวิเศษณ์ ต้องเลือกรูปให้ตรงกับตำแหน่งในประโยค' },
  groups:[ { en:'succeed', th:'สำเร็จ', words:'succeed (v) · success (n) · successful (adj) · successfully (adv)',
             wordsTh:'ประสบความสำเร็จ · ความสำเร็จ · ที่ประสบความสำเร็จ · อย่างประสบความสำเร็จ' },
           { en:'decide', th:'ตัดสินใจ', words:'decide (v) · decision (n) · decisive (adj) · decisively (adv)',
             wordsTh:'ตัดสินใจ · การตัดสินใจ · เด็ดขาด · อย่างเด็ดขาด' },
           { en:'care', th:'ใส่ใจ / ระวัง', words:'care (v) · care (n) · careful (adj) · carefully (adv)',
             wordsTh:'ใส่ใจ · ความใส่ใจ · ระมัดระวัง · อย่างระมัดระวัง' } ],
  rules:[ { en:'After a / the / my → noun.', th:'หลัง a / the / my → ใช้คำนาม',
            ok:'a good [decision]', okTh:'การตัดสินใจที่ดี', bad:'a good [decide]' },
          { en:'After to / can / will → verb.', th:'หลัง to / can / will → ใช้กริยา',
            ok:'I want to [improve].', okTh:'ฉันอยากพัฒนา', bad:'I want to [improvement].' },
          { en:'After is / very, or before a noun → adjective.', th:'หลัง is / very หรือหน้าคำนาม → ใช้คุณศัพท์',
            ok:'He is very [successful].', okTh:'เขาประสบความสำเร็จมาก', bad:'He is very [success].' },
          { en:'How someone does something → adverb.', th:'บอกว่าทำ "อย่างไร" → ใช้กริยาวิเศษณ์',
            ok:'Please drive [safely].', okTh:'โปรดขับรถอย่างปลอดภัย', bad:'Please drive [safety].' } ],
  clues:[ { pos:'noun', en:'-tion · -ness · -ment' }, { pos:'verb', en:'-ize · -ify · -en' },
          { pos:'adjective', en:'-ful · -ous · -ive' }, { pos:'adverb', en:'-ly' } ],
  clueNote:{ en:'Look at the word just before the gap: it tells you which form you need.', th:'ดูคำที่อยู่ก่อนช่องว่าง มันบอกได้ว่าต้องใช้รูปไหน' },
  tip:{ en:'English changes the form for each job: safe (adjective) → safety (noun) → safely (adverb).',
        th:'คำไทยคำเดียวใช้ได้หลายหน้าที่ (เช่น "ปลอดภัย") แต่ภาษาอังกฤษต้องเปลี่ยนรูป: safe → safety → safely' } },

{ // 10 Final boss
  q:{ en:'What job does each word do?', th:'แต่ละคำทำหน้าที่อะไร?' },
  def:{ en:'Every word in a sentence has a job. Find the job and you know the part of speech.',
        th:'ทุกคำในประโยคมีหน้าที่ของมัน ถ้ารู้หน้าที่ ก็จะรู้ว่าเป็นคำชนิดไหน' },
  groups:[ { pos:'noun', en:'names something', th:'เรียกชื่อ', words:'pizza · kitchen', wordsTh:'พิซซ่า · ห้องครัว' },
           { pos:'pronoun', en:'replaces a noun', th:'ใช้แทนคำนาม', words:'she · I', wordsTh:'เธอ · ฉัน' },
           { pos:'verb', en:'shows an action', th:'บอกการกระทำ', words:'ate', wordsTh:'กิน (อดีต)' },
           { pos:'adjective', en:'describes a noun', th:'ขยายคำนาม', words:'delicious', wordsTh:'อร่อย' },
           { pos:'adverb', en:'describes a verb', th:'ขยายกริยา', words:'quickly', wordsTh:'อย่างรวดเร็ว' },
           { pos:'preposition', en:'place or time', th:'บอกที่หรือเวลา', words:'in', wordsTh:'ใน' },
           { pos:'conjunction', en:'joins', th:'เชื่อม', words:'and', wordsTh:'และ' },
           { pos:'interjection', en:'shows a feeling', th:'แสดงอารมณ์', words:'Wow!', wordsTh:'ว้าว' } ],
  rules:[ { en:'Find the verb first: what happens?', th:'หากริยาก่อน: เกิดอะไรขึ้น?',
            ok:'She [ate] pizza.', okTh:'เธอกินพิซซ่า' },
          { en:'Who or what does it? That is a noun or a pronoun.', th:'ใครหรืออะไรเป็นผู้ทำ? นั่นคือคำนามหรือสรรพนาม',
            ok:'[She] ate [pizza].', okTh:'เธอกินพิซซ่า' },
          { en:'Describing words: adjective (for nouns), adverb (for verbs).', th:'คำที่ขยาย: คุณศัพท์ (ขยายนาม) กริยาวิเศษณ์ (ขยายกริยา)',
            ok:'[delicious] pizza · ate [quickly]', okTh:'พิซซ่าอร่อย · กินอย่างรวดเร็ว' },
          { en:'Small linking words: preposition (in, on) or conjunction (and, but).', th:'คำเล็ก ๆ ที่เชื่อม: บุพบท (in, on) หรือสันธาน (and, but)',
            ok:'[in] the kitchen · she [and] I', okTh:'ในห้องครัว · เธอและฉัน' } ],
  clues:[ { s:'What happens?', sTh:'เกิดอะไรขึ้น?', en:'verb', exTh:'กริยา' }, { s:'Who? What?', sTh:'ใคร? อะไร?', en:'noun / pronoun', exTh:'นาม / สรรพนาม' },
          { s:'What kind?', sTh:'แบบไหน?', en:'adjective', exTh:'คุณศัพท์' }, { s:'How?', sTh:'อย่างไร?', en:'adverb', exTh:'กริยาวิเศษณ์' } ],
  clueNote:{ en:'Ask a question about the word. The answer tells you its job.', th:'ตั้งคำถามกับคำนั้น คำตอบจะบอกหน้าที่ของมัน' },
  tip:{ en:'One word can change its job: a fast car (adjective), he runs fast (adverb).',
        th:'คำเดียวกันเปลี่ยนชนิดได้ตามหน้าที่ เช่น fast ใน "a fast car" (รถที่เร็ว) เป็นคุณศัพท์ แต่ใน "he runs fast" (เขาวิ่งเร็ว) เป็นกริยาวิเศษณ์' } },
];
EXPLAIN.forEach((x, i) => Object.assign(LEVELS[i], x));
