/* =========================================================
   Levels 6–10: Preposition, Conjunction, Interjection,
                Word Forms (mixed), Final Boss (all 8)
   ========================================================= */
LEVELS.push(
{ pos:'preposition', chips:['preposition'], topic:'Prepositions', th:'คำบุพบท (Preposition)',
  count:13, speed:1.35, spawn:2.7, maxAlive:4,
  items:[
    {t:'See you [on] Monday.', w:'See you [in] Monday.'},
    {t:'The class starts [at] 8 o\'clock.', w:'The class starts [on] 8 o\'clock.'},
    {t:'My birthday is [in] July.', w:'My birthday is [at] July.'},
    {t:'I was born [in] 2008.', w:'I was born [on] 2008.'},
    {t:'I am [at] home now.', w:'I am [in] home now.'},
    {t:'Please listen [to] the teacher.', w:'Please listen [at] the teacher.'},
    {t:'She is married [to] a doctor.', w:'She is married [with] a doctor.'},
    {t:'I am waiting [for] the bus.', w:'I am waiting [to] the bus.'},
    {t:'We go to school [by] bus.', w:'We go to school [with] bus.'},
    {t:'She is afraid [of] zombies.', w:'She is afraid [from] zombies.'},
    {t:'It depends [on] the weather.', w:'It depends [of] the weather.'},
    {t:'I have lived here [since] 2020.', w:'I have lived here [for] 2020.'},
  ],
  boss:[
    {t:'The zombie hid under the bed in my room during the storm.', th:'ซอมบี้ซ่อนอยู่ใต้เตียงในห้องของฉันระหว่างที่มีพายุ',
     stages:[{pos:'preposition', keys:['under','in','during']}], neutral:[]},
    {t:'We walked from the school to the park at noon.', th:'พวกเราเดินจากโรงเรียนไปสวนสาธารณะตอนเที่ยง',
     stages:[{pos:'preposition', keys:['from','to','at']}], neutral:[]},
  ] },

{ pos:'conjunction', chips:['conjunction'], topic:'Conjunctions', th:'คำสันธาน (Conjunction)',
  count:13, speed:1.35, spawn:2.7, maxAlive:4,
  items:[
    {t:'[Although] it rained, we played outside.', w:'[Although] it rained, [but] we played outside.', note:'only one joiner'},
    {t:'[Because] I was sick, I stayed home.', w:'[Because] I was sick, [so] I stayed home.', note:'only one joiner'},
    {t:'I like tea [and] coffee.', w:'I like tea [but] coffee.'},
    {t:'Do you want tea [or] coffee?', w:'Do you want tea [so] coffee?'},
    {t:'I was tired, [so] I went to bed.', w:'I was tired, [or] I went to bed.'},
    {t:'[Both] Tom [and] Anna are here.', w:'[Both] Tom [or] Anna are here.', note:'pair'},
    {t:'You can [either] stay [or] go.', w:'You can [either] stay [and] go.', note:'pair'},
    {t:'[Neither] Tom [nor] Anna came.', w:'[Neither] Tom [or] Anna came.', note:'pair'},
    {t:'She is poor [but] happy.', w:'She is poor [so] happy.'},
    {t:'Call me [when] you arrive.', w:'Call me [and] you arrive.'},
    {t:'I will go [if] it stops raining.', w:'I will go [but] it stops raining.'},
    {t:'He ran fast, [but] he missed the bus.', w:'He ran fast, [so] he missed the bus.'},
  ],
  boss:[
    {t:'I was tired but I kept running because the zombies were fast and hungry.', th:'ฉันเหนื่อยแต่ก็วิ่งต่อไป เพราะซอมบี้ทั้งเร็วและหิว',
     stages:[{pos:'conjunction', keys:['but','because','and']}], neutral:[]},
    {t:'You can stay or go, but call me when you get home.', th:'คุณจะอยู่หรือไปก็ได้ แต่โทรหาฉันเมื่อถึงบ้าน',
     stages:[{pos:'conjunction', keys:['or','but','when']}], neutral:[]},
  ] },

{ pos:'interjection', chips:['interjection'], topic:'Interjections', th:'คำอุทาน (Interjection)',
  count:14, speed:1.4, spawn:2.6, maxAlive:4,
  items:[
    {t:'[Ouch!] I hit my head.', w:'[Yum!] I hit my head.', note:'pain'},
    {t:'[Hooray!] We won the game!', w:'[Ouch!] We won the game!', note:'joy'},
    {t:'[Yuck!] This milk smells bad.', w:'[Yum!] This milk smells bad.', note:'disgust'},
    {t:'[Yum!] This cake is delicious.', w:'[Yuck!] This cake is delicious.', note:'tasty'},
    {t:'[Oops!] I dropped my phone.', w:'[Hooray!] I dropped my phone.', note:'small mistake'},
    {t:'[Shh!] Be quiet in the library.', w:'[Hooray!] Be quiet in the library.', note:'be quiet'},
    {t:'[Phew!] We escaped the zombies.', w:'[Yuck!] We escaped the zombies.', note:'relief'},
    {t:'[Wow!] What a beautiful view!', w:'[Ouch!] What a beautiful view!', note:'surprise'},
    {t:'[Oh no!] I forgot my homework.', w:'[Yum!] I forgot my homework.', note:'bad news'},
    {t:'[Hey!] Wait for me!', w:'[Yuck!] Wait for me!', note:'calling someone'},
    {t:'[Aha!] I found the answer.', w:'[Ouch!] I found the answer.', note:'discovery'},
    {t:'[Ugh!] I have to wake up early.', w:'[Yum!] I have to wake up early.', note:'annoyed'},
  ],
  boss:[
    {t:'Hey, wow, the zombies are dancing! Oops, I dropped my phone.', th:'เฮ้ ว้าว ซอมบี้กำลังเต้น! อุ๊ย ฉันทำโทรศัพท์หล่น',
     stages:[{pos:'interjection', keys:['hey','wow','oops']}], neutral:[]},
    {t:'Ouch! That hurt. Phew, it was only a small cut.', th:'โอ๊ย! เจ็บจัง เฮ้อ แค่แผลเล็ก ๆ เอง',
     stages:[{pos:'interjection', keys:['ouch','phew']}], neutral:[]},
  ] },

{ pos:null, chips:['noun','verb','adjective','adverb'], topic:'Word Forms', th:'การเปลี่ยนรูปคำ (n. · v. · adj. · adv.)',
  count:14, speed:1.45, spawn:2.5, maxAlive:4, bossSpeed:.42,
  items:[
    {t:'She made a good [decision].', w:'She made a good [decide].', pos:'noun'},
    {t:'He is very [successful].', w:'He is very [success].', pos:'adjective'},
    {t:'I want to [improve] my English.', w:'I want to [improvement] my English.', pos:'verb'},
    {t:'Education is very [important].', w:'Education is very [importance].', pos:'adjective'},
    {t:'Please drive [safely].', w:'Please drive [safety].', pos:'adverb'},
    {t:'Thank you for your [kindness].', w:'Thank you for your [kind].', pos:'noun'},
    {t:'The zombies [destroyed] the city.', w:'The zombies [destruction] the city.', pos:'verb'},
    {t:'She answered [confidently].', w:'She answered [confidence].', pos:'adverb'},
    {t:'This is a [dangerous] place.', w:'This is a [danger] place.', pos:'adjective'},
    {t:'We need more [information].', w:'We need more [inform].', pos:'noun'},
    {t:'Can you [explain] this word?', w:'Can you [explanation] this word?', pos:'verb'},
    {t:'The zombie moved [silently].', w:'The zombie moved [silence].', pos:'adverb'},
  ],
  boss:[
    {t:'The careful driver drives carefully because safety matters.', th:'คนขับที่ระมัดระวังขับรถอย่างระมัดระวัง เพราะความปลอดภัยเป็นเรื่องสำคัญ',
     stages:[{pos:'noun', keys:['driver','safety']}, {pos:'verb', keys:['drives','matters']},
             {pos:'adjective', keys:['careful']}, {pos:'adverb', keys:['carefully']}], neutral:['the']},
    {t:'The happy children sang happily and their happiness spread.', th:'เด็ก ๆ ที่มีความสุขร้องเพลงอย่างมีความสุข และความสุขของพวกเขาก็แผ่ขยายไป',
     stages:[{pos:'noun', keys:['children','happiness']}, {pos:'verb', keys:['sang','spread']},
             {pos:'adjective', keys:['happy']}, {pos:'adverb', keys:['happily']}], neutral:['the','their']},
  ] },

{ pos:null, chips:POS_ORDER, topic:'Final Boss: All 8 Parts of Speech', th:'บอสใหญ่: รวมชนิดของคำทั้ง 8 ชนิด',
  count:16, speed:1.5, spawn:2.4, maxAlive:5, bossSpeed:.36,
  items:[
    {t:'[They] gave [us] free pizza.', w:'[Them] gave [we] free pizza.', pos:'pronoun'},
    {t:'Two [knives] are on the table.', w:'Two [knifes] are on the table.', pos:'noun'},
    {t:'She [studies] English every day.', w:'She [study] English every day.', pos:'verb'},
    {t:'It was a [terrible] day.', w:'It was a [terribly] day.', pos:'adjective'},
    {t:'She [rarely] eats meat.', w:'She eats [rarely] meat.', pos:'adverb', note:'position'},
    {t:'The party is [on] Friday.', w:'The party is [at] Friday.', pos:'preposition'},
    {t:'[Although] he is rich, he is not happy.', w:'[Although] he is rich, [but] he is not happy.', pos:'conjunction'},
    {t:'[Wow!] You look amazing.', w:'[Yuck!] You look amazing.', pos:'interjection'},
    {t:'The zombie looks very [hungry].', w:'The zombie looks very [hunger].', pos:'adjective'},
    {t:'I [have] two sisters.', w:'I [has] two sisters.', pos:'verb'},
    {t:'We arrived [at] the station.', w:'We arrived [to] the station.', pos:'preposition'},
    {t:'I like this game [because] it is fun.', w:'I like this game [although] it is fun.', pos:'conjunction'},
    {t:'Three [sheep] are eating grass.', w:'Three [sheeps] are eating grass.', pos:'noun'},
    {t:'He speaks English [fluently].', w:'He speaks English [fluent].', pos:'adverb'},
  ],
  boss:[
    {t:'Wow! She and I quickly ate the delicious pizza in the kitchen.', th:'ว้าว! เธอกับฉันกินพิซซ่าแสนอร่อยในครัวอย่างรวดเร็ว',
     stages:[{pos:'noun', keys:['pizza','kitchen']}, {pos:'pronoun', keys:['she','I']}, {pos:'verb', keys:['ate']},
             {pos:'adjective', keys:['delicious']}, {pos:'adverb', keys:['quickly']}, {pos:'preposition', keys:['in']},
             {pos:'conjunction', keys:['and']}, {pos:'interjection', keys:['wow']}], neutral:['the']},
    {t:'Hooray! We found the hidden treasure under the old bridge and happily shared it.', th:'ไชโย! พวกเราเจอสมบัติที่ซ่อนอยู่ใต้สะพานเก่า แล้วแบ่งกันอย่างมีความสุข',
     stages:[{pos:'noun', keys:['treasure','bridge']}, {pos:'pronoun', keys:['we','it']}, {pos:'verb', keys:['found','shared']},
             {pos:'adjective', keys:['hidden','old']}, {pos:'adverb', keys:['happily']}, {pos:'preposition', keys:['under']},
             {pos:'conjunction', keys:['and']}, {pos:'interjection', keys:['hooray']}], neutral:['the']},
  ] },
);
