/* =========================================================
   Lesson 2 · Tenses, levels 5–8: Present Perfect, Future, Time Words, Final (all tenses)
   (format: see levels-3.js)
   ========================================================= */
LEVELS.push(
{ unit:'tense', pos:'presentPerfect', chips:['presentPerfect','timeWord'], topic:'Present Perfect', th:'ปัจจุบันสมบูรณ์ (Present Perfect)',
  count:12, speed:1.3, spawn:2.8, maxAlive:4,
  items:[
    {t:'I [have finished] my homework.', w:'I [have finish] my homework.'},
    {t:'She [has lived] here for ten years.', w:'She [have lived] here for ten years.'},
    {t:'We [have known] each other since 2019.', w:'We [know] each other since 2019.'},
    {t:'Have you ever [eaten] durian?', w:'Have you ever [ate] durian?'},
    {t:'He [has never been] to Japan.', w:'He [has never went] to Japan.'},
    {t:'I [saw] him yesterday.', w:'I [have seen] him yesterday.', pos:'pastSimple', note:'finished time'},
    {t:'They [have just arrived].', w:'They [have just arrive].'},
    {t:'[Has] she called you yet?', w:'[Have] she called you yet?'},
    {t:'I [have written] three emails today.', w:'I [have wrote] three emails today.'},
    {t:'The movie [has already started].', w:'The movie [has already start].'},
  ],
  boss:[
    {t:'I have lived in Bangkok since 2015 and have never seen snow.', th:'ฉันอาศัยอยู่ในกรุงเทพฯ ตั้งแต่ปี 2015 และไม่เคยเห็นหิมะเลย',
     stages:[{pos:'timeWord', keys:['since','never']}, {pos:'presentPerfect', keys:['have','lived','have','seen']}], neutral:['2015']},
    {t:'She has already eaten, but he has not eaten yet.', th:'เธอกินไปแล้ว แต่เขายังไม่ได้กิน',
     stages:[{pos:'timeWord', keys:['already','yet']}, {pos:'presentPerfect', keys:['has','eaten','has','eaten']}], neutral:['not']},
  ],
  q:{ en:'What has happened up to now?', th:'อะไรเกิดขึ้นแล้วบ้างจนถึงตอนนี้?' },
  def:{ en:'The present perfect links the past to now: have / has + verb 3. I have lived here for ten years (and I still live here).',
        th:'Present Perfect เชื่อมอดีตกับตอนนี้: have / has + กริยาช่อง 3 เช่น I have lived here for ten years. (ฉันอาศัยอยู่ที่นี่มา 10 ปีแล้ว และตอนนี้ก็ยังอยู่)' },
  groups:[ { en:'I / you / we / they', th:'ใช้ have', words:'have finished · have seen', wordsTh:'ทำเสร็จแล้ว · เคยเห็น' },
           { en:'he / she / it', th:'ใช้ has', words:'has eaten · has been', wordsTh:'กินแล้ว · เคยไป' },
           { en:'verb 3', th:'กริยาช่อง 3', words:'eaten · written · gone · seen', wordsTh:'กิน · เขียน · ไป · เห็น' } ],
  rules:[ { en:'have / has + verb 3 (not verb 1 or verb 2).', th:'have / has + กริยาช่อง 3 (ไม่ใช่ช่อง 1 หรือช่อง 2)',
            ok:'I [have finished] my work.', okTh:'ฉันทำงานเสร็จแล้ว', bad:'I [have finish] my work.' },
          { en:'he / she / it → has. Everyone else → have.', th:'he / she / it ใช้ has นอกนั้นใช้ have',
            ok:'She [has lived] here for years.', okTh:'เธออาศัยอยู่ที่นี่มาหลายปีแล้ว', bad:'She [have lived] here for years.' },
          { en:'Life experience: ever / never + verb 3.', th:'ประสบการณ์ชีวิต: ever / never + กริยาช่อง 3',
            ok:'Have you ever [eaten] durian?', okTh:'คุณเคยกินทุเรียนไหม?', bad:'Have you ever [ate] durian?' },
          { en:'A finished time (yesterday, last week) → past simple, not present perfect.', th:'ถ้าบอกเวลาที่จบไปแล้ว (yesterday, last week) → ใช้ Past Simple ไม่ใช่ Present Perfect',
            ok:'I [saw] her yesterday.', okTh:'ฉันเห็นเธอเมื่อวาน', bad:'I [have seen] her yesterday.' } ],
  clues:[ { s:'for', sTh:'เป็นเวลา', en:'for ten years', exTh:'เป็นเวลา 10 ปี' }, { s:'since', sTh:'ตั้งแต่', en:'since 2020', exTh:'ตั้งแต่ปี 2020' },
          { s:'already', sTh:'แล้ว', en:'she has already left', exTh:'เธอไปแล้ว' }, { s:'yet', sTh:'ยัง', en:"I haven't eaten yet", exTh:'ฉันยังไม่ได้กิน' },
          { s:'ever / never', sTh:'เคย / ไม่เคย', en:'I have never seen snow', exTh:'ฉันไม่เคยเห็นหิมะ' } ],
  clueNote:{ en:'These words link the past to now, so use have / has + verb 3.', th:'คำเหล่านี้เชื่อมอดีตกับตอนนี้ จึงใช้ have / has + กริยาช่อง 3' },
  tip:{ en:'Thai says เคย or แล้ว and keeps the verb the same. English needs have / has + verb 3: I have eaten.',
        th:'ภาษาไทยใช้คำว่า "เคย" หรือ "แล้ว" โดยกริยาไม่เปลี่ยน แต่ภาษาอังกฤษต้องใช้ have / has + กริยาช่อง 3 เช่น I have eaten. (ฉันกินแล้ว)' } },

{ unit:'tense', pos:'future', chips:['future','timeWord'], topic:'Future', th:'อนาคต (will / going to)',
  count:13, speed:1.35, spawn:2.7, maxAlive:4,
  items:[
    {t:'I [will call] you tomorrow.', w:'I [will calling] you tomorrow.'},
    {t:'It [is going to rain]. Look at the clouds!', w:'It [going to rain]. Look at the clouds!'},
    {t:'She [will be] 15 next month.', w:'She [will is] 15 next month.'},
    {t:'We [are going to visit] Chiang Mai next week.', w:'We [are going to visited] Chiang Mai next week.'},
    {t:'[Will] you help me tomorrow?', w:'[Do] you help me tomorrow?'},
    {t:"He [won't come] to the party.", w:"He [won't comes] to the party."},
    {t:'I think it [will be] sunny tomorrow.', w:'I think it [be] sunny tomorrow.'},
    {t:'They [are going to buy] a new car.', w:'They [is going to buy] a new car.'},
    {t:'I [am going to study] tonight.', w:'I [am going to studying] tonight.'},
    {t:'The shop [will open] at nine tomorrow.', w:'The shop [opened] at nine tomorrow.'},
  ],
  boss:[
    {t:'Tomorrow I will visit my grandma and we are going to cook together.', th:'พรุ่งนี้ฉันจะไปเยี่ยมยาย และเราจะทำอาหารด้วยกัน',
     stages:[{pos:'timeWord', keys:['tomorrow']}, {pos:'future', keys:['will','visit','are','going','to','cook']}], neutral:[]},
    {t:'Next week the zombies will attack, so we are going to hide.', th:'สัปดาห์หน้าซอมบี้จะบุก เราจึงจะไปซ่อนตัว',
     stages:[{pos:'timeWord', keys:['next','week']}, {pos:'future', keys:['will','attack','are','going','to','hide']}], neutral:[]},
  ],
  q:{ en:'What will happen later?', th:'จะเกิดอะไรขึ้นในอนาคต?' },
  def:{ en:'For the future use will + base verb (quick decisions, predictions) or am / is / are going to + base verb (plans, things we can see coming).',
        th:'อนาคตใช้ will + กริยาช่อง 1 (ตัดสินใจตอนนั้นเลย หรือคาดเดา) หรือ am / is / are going to + กริยาช่อง 1 (แผนที่วางไว้ หรือสิ่งที่เห็นแนวโน้มแล้ว)' },
  groups:[ { en:'will', th:'จะ', words:"will call · will be · won't come", wordsTh:'จะโทร · จะเป็น · จะไม่มา' },
           { en:'be going to', th:'ตั้งใจจะ / กำลังจะ', words:'am going to study · is going to rain · are going to visit', wordsTh:'ตั้งใจจะเรียน · ฝนกำลังจะตก · ตั้งใจจะไปเยี่ยม' } ],
  rules:[ { en:'will + the base verb (no -s, no -ing, no -ed).', th:'will + กริยาช่อง 1 เปล่า ๆ (ไม่เติม -s, -ing หรือ -ed)',
            ok:'I [will call] you later.', okTh:'เดี๋ยวฉันจะโทรหาคุณ', bad:'I [will calling] you later.' },
          { en:'going to needs am / is / are in front.', th:'going to ต้องมี am / is / are นำหน้า',
            ok:'It [is going to rain].', okTh:'ฝนกำลังจะตก', bad:'It [going to rain].' },
          { en:'After going to → the base verb.', th:'หลัง going to → ใช้กริยาช่อง 1',
            ok:'We [are going to visit] Chiang Mai.', okTh:'เราตั้งใจจะไปเที่ยวเชียงใหม่', bad:'We [are going to visited] Chiang Mai.' },
          { en:'A future time word needs a future verb.', th:'คำบอกเวลาในอนาคต ต้องใช้กริยาแบบอนาคต',
            ok:'The bank [will open] tomorrow.', okTh:'ธนาคารจะเปิดพรุ่งนี้', bad:'The bank [opened] tomorrow.' } ],
  clues:[ { s:'tomorrow', sTh:'พรุ่งนี้', en:'I will see you tomorrow', exTh:'พรุ่งนี้เจอกัน' }, { s:'next week', sTh:'สัปดาห์หน้า', en:'we are going to travel next week', exTh:'สัปดาห์หน้าเราจะไปเที่ยว' },
          { s:'soon', sTh:'เร็ว ๆ นี้', en:'it will be ready soon', exTh:'อีกไม่นานจะเสร็จ' }, { s:'I think', sTh:'ฉันคิดว่า', en:'I think it will rain', exTh:'ฉันคิดว่าฝนจะตก' } ],
  clueNote:{ en:'These words point to the future: will or be going to + base verb.', th:'คำเหล่านี้บอกอนาคต: ใช้ will หรือ be going to + กริยาช่อง 1' },
  tip:{ en:'Thai just adds จะ before the verb. English also needs the right verb form after it: will + base verb, never will + -ing.',
        th:'ภาษาไทยแค่เติม "จะ" หน้ากริยา แต่ภาษาอังกฤษต้องใช้รูปกริยาให้ถูกด้วย: will + กริยาช่อง 1 ห้ามใช้ will + -ing' } },

{ unit:'tense', pos:'timeWord', chips:['timeWord','pastSimple','presentPerfect','future'], topic:'Time Words', th:'คำบอกเวลา (Time Words)',
  count:13, speed:1.35, spawn:2.7, maxAlive:4,
  items:[
    {t:'I have lived here [for] three years.', w:'I have lived here [since] three years.'},
    {t:'She has worked here [since] 2020.', w:'She has worked here [for] 2020.'},
    {t:'I met him two days [ago].', w:'I met him [ago] two days.'},
    {t:"I haven't eaten [yet].", w:"I haven't eaten [already]."},
    {t:'She has [already] left.', w:'She has [yet] left.'},
    {t:'I visited Chiang Mai [last] year.', w:'I visited Chiang Mai [next] year.'},
    {t:'We will travel to Japan [next] month.', w:'We will travel to Japan [last] month.'},
    {t:'Look! It is raining [now].', w:'Look! It is raining [yesterday].'},
    {t:'I have [never] seen snow.', w:'I have [ever] seen snow.'},
    {t:'It stopped raining an hour [ago].', w:'It stopped raining [since] an hour.'},
  ],
  boss:[
    {t:'Yesterday I was busy, but tomorrow I will be free.', th:'เมื่อวานฉันยุ่ง แต่พรุ่งนี้ฉันจะว่าง',
     stages:[{pos:'timeWord', keys:['yesterday','tomorrow']}, {pos:'pastSimple', keys:['was']}, {pos:'future', keys:['will','be']}], neutral:[]},
    {t:'I moved here two years ago and I have lived here since then.', th:'ฉันย้ายมาที่นี่เมื่อสองปีที่แล้ว และอาศัยอยู่ที่นี่ตั้งแต่นั้นมา',
     stages:[{pos:'timeWord', keys:['ago','since','then']}, {pos:'pastSimple', keys:['moved']}, {pos:'presentPerfect', keys:['have','lived']}], neutral:['two','years']},
  ],
  q:{ en:'When? The time word picks the tense.', th:'เมื่อไร? คำบอกเวลาเป็นตัวเลือก tense' },
  def:{ en:'Time words tell us when something happens, so they must match the tense: yesterday → past, now → present continuous, tomorrow → future.',
        th:'คำบอกเวลาบอกว่าเรื่องเกิดขึ้นเมื่อไร จึงต้องเข้ากับ tense เช่น yesterday → อดีต, now → กำลังทำ, tomorrow → อนาคต' },
  groups:[ { en:'past', th:'อดีต', words:'yesterday · last year · ago', wordsTh:'เมื่อวาน · ปีที่แล้ว · ที่แล้ว' },
           { en:'now', th:'ตอนนี้', words:'now · at the moment', wordsTh:'ตอนนี้ · ขณะนี้' },
           { en:'past until now', th:'อดีตจนถึงตอนนี้', words:'for · since · already · yet', wordsTh:'เป็นเวลา · ตั้งแต่ · แล้ว · ยัง' },
           { en:'future', th:'อนาคต', words:'tomorrow · next week · soon', wordsTh:'พรุ่งนี้ · สัปดาห์หน้า · เร็ว ๆ นี้' } ],
  rules:[ { en:'for + a length of time, since + a starting point.', th:'for + ระยะเวลา ส่วน since + จุดเริ่มต้น',
            ok:'[for] three years · [since] 2020', okTh:'เป็นเวลา 3 ปี · ตั้งแต่ปี 2020', bad:'[since] three years' },
          { en:'ago goes after the time and uses the past simple.', th:'ago วางหลังระยะเวลา และใช้กับ Past Simple',
            ok:'two days [ago]', okTh:'เมื่อสองวันที่แล้ว', bad:'[ago] two days' },
          { en:'already in positive sentences, yet in questions and "not" sentences.', th:'already ใช้ในประโยคบอกเล่า ส่วน yet ใช้ในคำถามและประโยคปฏิเสธ',
            ok:"She has [already] gone. · I haven't paid [yet].", okTh:'เธอไปแล้ว · ฉันยังไม่ได้จ่ายเงิน', bad:"I haven't paid [already]." },
          { en:'last = the one before (past), next = the one after (future).', th:'last = ที่แล้ว (อดีต) ส่วน next = หน้า / ถัดไป (อนาคต)',
            ok:'I went there [last] year.', okTh:'ฉันไปที่นั่นเมื่อปีที่แล้ว', bad:'I went there [next] year.' } ],
  clues:[ { s:'yesterday', sTh:'เมื่อวาน', en:'past simple', exTh:'อดีตธรรมดา' }, { s:'now', sTh:'ตอนนี้', en:'present continuous', exTh:'ปัจจุบันกำลังทำ' },
          { s:'since', sTh:'ตั้งแต่', en:'present perfect', exTh:'ปัจจุบันสมบูรณ์' }, { s:'tomorrow', sTh:'พรุ่งนี้', en:'future', exTh:'อนาคต' } ],
  clueNote:{ en:'Find the time word first. It tells you which tense the verb needs.', th:'หาคำบอกเวลาก่อน แล้วจะรู้ว่ากริยาต้องใช้ tense ไหน' },
  tip:{ en:'In Thai the time word does all the work. In English the time word and the verb must agree.',
        th:'ภาษาไทยใช้คำบอกเวลาบอกทุกอย่าง แต่ภาษาอังกฤษคำบอกเวลากับกริยาต้องไปด้วยกัน' } },

{ unit:'tense', pos:null, chips:TENSE_ORDER, topic:'Final Boss: All Tenses', th:'บอสใหญ่: รวมทุก Tense',
  count:16, speed:1.5, spawn:2.4, maxAlive:5, bossSpeed:.36,
  items:[
    {t:'He [drinks] milk every morning.', w:'He [drink] milk every morning.', pos:'presentSimple'},
    {t:'Be quiet! The baby [is sleeping].', w:'Be quiet! The baby [sleeps].', pos:'presentCont'},
    {t:'We [watched] a movie last night.', w:'We [watch] a movie last night.', pos:'pastSimple'},
    {t:'I [was taking] a shower when you called.', w:'I [was take] a shower when you called.', pos:'pastCont'},
    {t:'She [has worked] here since 2018.', w:'She [works] here since 2018.', pos:'presentPerfect'},
    {t:'I [will help] you tomorrow.', w:'I [helped] you tomorrow.', pos:'future'},
    {t:'They [went] home two hours ago.', w:'They [have gone] home two hours ago.', pos:'pastSimple'},
    {t:'Have you [seen] my keys?', w:'Have you [saw] my keys?', pos:'presentPerfect'},
    {t:'Look! It [is snowing].', w:'Look! It [snows].', pos:'presentCont'},
    {t:'We [are going to travel] next summer.', w:'We [going to travel] next summer.', pos:'future'},
    {t:"My sister [doesn't eat] fish.", w:'My sister [not eat] fish.', pos:'presentSimple'},
    {t:"I haven't finished it [yet].", w:"I haven't finished it [already].", pos:'timeWord'},
  ],
  boss:[
    {t:'Yesterday I lost my phone, so now I am looking for it, and tomorrow I will buy a new one.',
     th:'เมื่อวานฉันทำโทรศัพท์หาย ตอนนี้ฉันเลยกำลังตามหามันอยู่ และพรุ่งนี้ฉันจะซื้อเครื่องใหม่',
     stages:[{pos:'timeWord', keys:['yesterday','now','tomorrow']}, {pos:'pastSimple', keys:['lost']},
             {pos:'presentCont', keys:['am','looking']}, {pos:'future', keys:['will','buy']}], neutral:[]},
    {t:'I have lived here since May, but last year I was living in Phuket.',
     th:'ฉันอาศัยอยู่ที่นี่ตั้งแต่เดือนพฤษภาคม แต่ปีที่แล้วฉันอาศัยอยู่ที่ภูเก็ต',
     stages:[{pos:'timeWord', keys:['since','last','year']}, {pos:'presentPerfect', keys:['have','lived']},
             {pos:'pastCont', keys:['was','living']}], neutral:['may']},
  ],
  q:{ en:'Which time? Which tense?', th:'เวลาไหน? ใช้ tense ไหน?' },
  def:{ en:'Every tense in one level. Look for the time word first, then check the verb form.',
        th:'รวมทุก tense ไว้ในด่านเดียว หาคำบอกเวลาก่อน แล้วค่อยเช็กรูปกริยา' },
  groups:[ { pos:'presentSimple', en:'habits', th:'นิสัย / ความจริง', words:'she plays', wordsTh:'เธอเล่น (เป็นประจำ)' },
           { pos:'presentCont', en:'right now', th:'ตอนนี้', words:'she is playing', wordsTh:'เธอกำลังเล่น' },
           { pos:'pastSimple', en:'finished', th:'จบแล้ว', words:'she played', wordsTh:'เธอเล่นแล้ว' },
           { pos:'pastCont', en:'in progress then', th:'กำลังทำอยู่ตอนนั้น', words:'she was playing', wordsTh:'ตอนนั้นเธอกำลังเล่น' },
           { pos:'presentPerfect', en:'past until now', th:'อดีตจนถึงตอนนี้', words:'she has played', wordsTh:'เธอเล่นมาแล้ว / เคยเล่น' },
           { pos:'future', en:'later', th:'อนาคต', words:'she will play', wordsTh:'เธอจะเล่น' } ],
  rules:[ { en:'Find the time word first: it tells you the tense.', th:'หาคำบอกเวลาก่อน มันบอกว่าต้องใช้ tense ไหน',
            ok:'We watched a movie [last night].', okTh:'เมื่อคืนเราดูหนัง' },
          { en:'Then check the helper: do / does, am / is / are, was / were, have / has, will.', th:'แล้วเช็กตัวช่วย: do / does, am / is / are, was / were, have / has, will',
            ok:'She [has] worked here since 2018.', okTh:'เธอทำงานที่นี่ตั้งแต่ปี 2018' },
          { en:'Last, check the verb form: base, -s, -ing, verb 2 or verb 3.', th:'สุดท้ายเช็กรูปกริยา: ช่อง 1, เติม -s, เติม -ing, ช่อง 2 หรือช่อง 3',
            ok:'Have you [seen] my keys?', okTh:'คุณเห็นกุญแจของฉันไหม?', bad:'Have you [saw] my keys?' } ],
  clues:[ { s:'every day', sTh:'ทุกวัน', en:'present simple', exTh:'ปัจจุบันธรรมดา' }, { s:'now', sTh:'ตอนนี้', en:'present continuous', exTh:'ปัจจุบันกำลังทำ' },
          { s:'yesterday', sTh:'เมื่อวาน', en:'past simple', exTh:'อดีตธรรมดา' }, { s:'when / while', sTh:'ตอนที่ / ขณะที่', en:'past continuous', exTh:'อดีตกำลังทำ' },
          { s:'for / since', sTh:'เป็นเวลา / ตั้งแต่', en:'present perfect', exTh:'ปัจจุบันสมบูรณ์' }, { s:'tomorrow', sTh:'พรุ่งนี้', en:'future', exTh:'อนาคต' } ],
  clueNote:{ en:'Each time word points to one tense.', th:'คำบอกเวลาแต่ละคำชี้ไปที่ tense หนึ่ง' },
  tip:{ en:'Thai can say ฉันกิน for any time. English must change the verb: eat, am eating, ate, have eaten, will eat.',
        th:'ภาษาไทยพูด "ฉันกิน" ได้ทุกเวลา แต่ภาษาอังกฤษต้องเปลี่ยนกริยา: eat, am eating, ate, have eaten, will eat' } },
);
