/* =========================================================
   Lesson 2 · Tenses, levels 1–4: Present Simple, Present Continuous, Past Simple, Past Continuous
   Same format as levels-1.js (items, boss), with the teaching text of explain.js kept in the level itself.
   pos = the tense of the highlighted verb; timeWord = words that tell which tense to use
   ========================================================= */
LEVELS.push(
{ unit:'tense', pos:'presentSimple', chips:['presentSimple','timeWord'], topic:'Present Simple', th:'ปัจจุบันธรรมดา (Present Simple)',
  count:8, speed:1.15, spawn:3.4, maxAlive:2,
  items:[
    {t:'She [goes] to school by bus.', w:'She [go] to school by bus.'},
    {t:'The sun [rises] in the east.', w:'The sun [rise] in the east.'},
    {t:'My father [watches] the news every night.', w:'My father [watch] the news every night.'},
    {t:'They [play] football every Sunday.', w:'They [plays] football every Sunday.'},
    {t:"He [doesn't like] coffee.", w:"He [don't like] coffee."},
    {t:'[Does] she speak English?', w:'[Do] she speak English?'},
    {t:'I [live] in Chiang Mai.', w:'I [am live] in Chiang Mai.'},
    {t:'Water [boils] at 100 degrees.', w:'Water [is boil] at 100 degrees.'},
    {t:'My brother [studies] every evening.', w:'My brother [studys] every evening.'},
    {t:"We [don't eat] meat.", w:"We [doesn't eat] meat."},
  ],
  boss:[
    {t:'Every morning my mother cooks rice and my father drinks coffee.', th:'ทุกเช้าแม่ของฉันหุงข้าว และพ่อของฉันดื่มกาแฟ',
     stages:[{pos:'timeWord', keys:['every','morning']}, {pos:'presentSimple', keys:['cooks','drinks']}], neutral:[]},
    {t:'She usually walks to school, but her brother takes the bus.', th:'ปกติเธอเดินไปโรงเรียน แต่น้องชายของเธอนั่งรถบัส',
     stages:[{pos:'timeWord', keys:['usually']}, {pos:'presentSimple', keys:['walks','takes']}], neutral:[]},
  ],
  q:{ en:'What happens again and again?', th:'อะไรเกิดขึ้นเป็นประจำ?' },
  def:{ en:'The present simple is for habits, routines and facts that are always true: I walk to school. The sun rises in the east.',
        th:'Present Simple ใช้กับนิสัย กิจวัตร และความจริงที่เป็นจริงเสมอ เช่น I walk to school. (ฉันเดินไปโรงเรียน) The sun rises in the east. (ดวงอาทิตย์ขึ้นทางทิศตะวันออก)' },
  groups:[ { en:'I / you / we / they', th:'ประธานทั่วไป ใช้กริยาเปล่า ๆ', words:'play · eat · go', wordsTh:'เล่น · กิน · ไป' },
           { en:'he / she / it', th:'ประธานเอกพจน์ เติม -s', words:'plays · eats · goes', wordsTh:'เล่น · กิน · ไป' },
           { en:'not', th:'ปฏิเสธ', words:"don't play · doesn't play", wordsTh:'ไม่เล่น · ไม่เล่น (he / she / it)' } ],
  rules:[ { en:'he / she / it → add -s or -es to the verb.', th:'ประธาน he / she / it → กริยาเติม -s หรือ -es',
            ok:'She [goes] · He [watches]', okTh:'เธอไป · เขาดู', bad:'She [go] to school.' },
          { en:'Consonant + y → -ies: study → studies.', th:'พยัญชนะ + y → เปลี่ยนเป็น -ies เช่น study → studies',
            ok:'He [studies] every day.', okTh:'เขาเรียนทุกวัน', bad:'He [studys] every day.' },
          { en:'Not and questions: do / does + the base verb (no -s).', th:'ปฏิเสธและคำถาม: do / does + กริยาช่อง 1 (ไม่เติม -s)',
            ok:"He [doesn't like] it. · [Does] she swim?", okTh:'เขาไม่ชอบมัน · เธอว่ายน้ำไหม?', bad:"He [don't like] it." },
          { en:'No am / is / are before an action verb.', th:'ห้ามใช้ am / is / are นำหน้ากริยาที่บอกการกระทำ',
            ok:'I [live] in Bangkok.', okTh:'ฉันอาศัยอยู่ในกรุงเทพฯ', bad:'I [am live] in Bangkok.' } ],
  clues:[ { s:'always', sTh:'เสมอ', en:'she always walks', exTh:'เธอเดินเสมอ' }, { s:'usually', sTh:'โดยปกติ', en:'I usually eat rice', exTh:'ปกติฉันกินข้าว' },
          { s:'every day', sTh:'ทุกวัน', en:'he plays every day', exTh:'เขาเล่นทุกวัน' }, { s:'on Sundays', sTh:'ทุกวันอาทิตย์', en:'we swim on Sundays', exTh:'เราว่ายน้ำทุกวันอาทิตย์' } ],
  clueNote:{ en:'These words mean "again and again", so use the present simple.', th:'คำเหล่านี้แปลว่า "ทำซ้ำ ๆ เป็นประจำ" จึงใช้ Present Simple' },
  tip:{ en:'Thai verbs never change (ฉันไป, เขาไป), so Thai speakers often forget the -s after he / she / it.',
        th:'กริยาไทยไม่เปลี่ยนรูป (ฉันไป, เขาไป) คนไทยจึงมักลืมเติม -s หลัง he / she / it' } },

{ unit:'tense', pos:'presentCont', chips:['presentCont','timeWord'], topic:'Present Continuous', th:'ปัจจุบันกำลังทำ (Present Continuous)',
  count:10, speed:1.2, spawn:3.2, maxAlive:3,
  items:[
    {t:'Look! The baby [is sleeping].', w:'Look! The baby [sleeping].'},
    {t:'I [am reading] a book right now.', w:'I [am read] a book right now.'},
    {t:'They [are playing] games at the moment.', w:'They [is playing] games at the moment.'},
    {t:'Listen! Someone [is singing].', w:'Listen! Someone [sings].'},
    {t:'She [is running] in the park now.', w:'She [is runing] in the park now.'},
    {t:'We [are making] a cake.', w:'We [are makeing] a cake.'},
    {t:'I [know] the answer.', w:'I [am knowing] the answer.', pos:'presentSimple', note:'feeling verb'},
    {t:'He [is not watching] TV now.', w:'He [not watching] TV now.'},
    {t:'[Are] you listening to me?', w:'[Do] you listening to me?'},
    {t:'The children [are swimming] now.', w:'The children [are swiming] now.'},
  ],
  boss:[
    {t:'Right now my sister is cooking and my brothers are playing games.', th:'ตอนนี้พี่สาวของฉันกำลังทำอาหาร และพี่ชายของฉันกำลังเล่นเกม',
     stages:[{pos:'timeWord', keys:['right','now']}, {pos:'presentCont', keys:['is','cooking','are','playing']}], neutral:[]},
    {t:'Look! The dog is chasing the cat and the birds are singing.', th:'ดูสิ! สุนัขกำลังไล่แมว และนกกำลังร้องเพลง',
     stages:[{pos:'presentCont', keys:['is','chasing','are','singing']}], neutral:['look']},
  ],
  q:{ en:'What is happening right now?', th:'ตอนนี้กำลังเกิดอะไรขึ้น?' },
  def:{ en:'The present continuous is for actions happening right now: am / is / are + verb-ing. Look! It is raining.',
        th:'Present Continuous ใช้กับสิ่งที่กำลังเกิดขึ้นตอนนี้: am / is / are + กริยาเติม -ing เช่น Look! It is raining. (ดูสิ! ฝนกำลังตก)' },
  groups:[ { en:'I', th:'ใช้ am', words:'am reading', wordsTh:'กำลังอ่าน' },
           { en:'he / she / it', th:'ใช้ is', words:'is eating · is sleeping', wordsTh:'กำลังกิน · กำลังนอน' },
           { en:'you / we / they', th:'ใช้ are', words:'are playing · are running', wordsTh:'กำลังเล่น · กำลังวิ่ง' } ],
  rules:[ { en:'You need BOTH parts: am / is / are + -ing.', th:'ต้องมีครบทั้งสองส่วน: am / is / are + -ing',
            ok:'The baby [is sleeping].', okTh:'เด็กทารกกำลังนอนหลับ', bad:'The baby [sleeping].' },
          { en:'Match the helper to the subject: I am, he is, they are.', th:'ตัวช่วยต้องตรงกับประธาน: I am, he is, they are',
            ok:'They [are playing].', okTh:'พวกเขากำลังเล่น', bad:'They [is playing].' },
          { en:'Spelling: run → running (double the letter), make → making (drop the e).', th:'การสะกด: run → running (เพิ่มตัวสะกดซ้ำ) make → making (ตัด e ทิ้ง)',
            ok:'[running] · [making] · [swimming]', okTh:'กำลังวิ่ง · กำลังทำ · กำลังว่ายน้ำ', bad:'She is [runing].' },
          { en:"Feeling and knowing verbs (know, like, want) don't take -ing.", th:'กริยาที่บอกความรู้สึกหรือความรู้ (know, like, want) ไม่ใช้ -ing',
            ok:'I [know] the answer.', okTh:'ฉันรู้คำตอบ', bad:'I [am knowing] the answer.' } ],
  clues:[ { s:'now', sTh:'ตอนนี้', en:'I am eating now', exTh:'ตอนนี้ฉันกำลังกิน' }, { s:'right now', sTh:'ตอนนี้เลย', en:'she is working right now', exTh:'ตอนนี้เธอกำลังทำงาน' },
          { s:'at the moment', sTh:'ขณะนี้', en:'they are studying at the moment', exTh:'ขณะนี้พวกเขากำลังเรียน' }, { s:'Look! / Listen!', sTh:'ดูสิ! / ฟังสิ!', en:'Look! It is snowing.', exTh:'ดูสิ! หิมะกำลังตก' } ],
  clueNote:{ en:'These words point to "right now", so use am / is / are + -ing.', th:'คำเหล่านี้หมายถึง "ตอนนี้" จึงใช้ am / is / are + -ing' },
  tip:{ en:'Thai just adds กำลัง, but English needs two parts: is + eating. Thai speakers often drop am / is / are.',
        th:'ภาษาไทยแค่เติม "กำลัง" แต่ภาษาอังกฤษต้องมีสองส่วน คือ is + eating คนไทยจึงมักลืม am / is / are' } },

{ unit:'tense', pos:'pastSimple', chips:['pastSimple','timeWord'], topic:'Past Simple', th:'อดีตธรรมดา (Past Simple)',
  count:11, speed:1.25, spawn:3.0, maxAlive:3,
  items:[
    {t:'I [went] to the beach yesterday.', w:'I [go] to the beach yesterday.'},
    {t:'She [visited] her grandma last week.', w:'She [visit] her grandma last week.'},
    {t:'We [ate] pizza last night.', w:'We [eated] pizza last night.'},
    {t:"He [didn't see] the movie.", w:"He [didn't saw] the movie."},
    {t:'[Did] you call me last night?', w:'[Do] you call me last night?'},
    {t:'They [were] at home last Sunday.', w:'They [was] at home last Sunday.'},
    {t:'I [bought] a new phone two days ago.', w:'I [buyed] a new phone two days ago.'},
    {t:'The train [stopped] suddenly.', w:'The train [stoped] suddenly.'},
    {t:'She [was] tired yesterday.', w:'She [is] tired yesterday.'},
    {t:'My dad [taught] me to swim.', w:'My dad [teached] me to swim.'},
  ],
  boss:[
    {t:'Yesterday I went to the market and bought some mangoes.', th:'เมื่อวานฉันไปตลาดและซื้อมะม่วงมาบ้าง',
     stages:[{pos:'timeWord', keys:['yesterday']}, {pos:'pastSimple', keys:['went','bought']}], neutral:[]},
    {t:'Last night the zombie ate my pizza and drank my milk.', th:'เมื่อคืนซอมบี้กินพิซซ่าของฉันและดื่มนมของฉัน',
     stages:[{pos:'timeWord', keys:['last','night']}, {pos:'pastSimple', keys:['ate','drank']}], neutral:[]},
  ],
  q:{ en:'What happened and is finished?', th:'เกิดอะไรขึ้นและจบไปแล้ว?' },
  def:{ en:'The past simple is for actions that started and finished in the past: I went to the beach yesterday.',
        th:'Past Simple ใช้กับเรื่องที่เกิดขึ้นและจบไปแล้วในอดีต เช่น I went to the beach yesterday. (เมื่อวานฉันไปทะเล)' },
  groups:[ { en:'regular: add -ed', th:'กริยาปกติ เติม -ed', words:'played · visited · stopped', wordsTh:'เล่นแล้ว · ไปเยี่ยมแล้ว · หยุดแล้ว' },
           { en:'irregular: learn them', th:'กริยาผิดปกติ ต้องจำ', words:'went · ate · saw · bought', wordsTh:'ไป · กิน · เห็น · ซื้อ' },
           { en:'be', th:'เป็น / อยู่', words:'was · were', wordsTh:'ใช้กับ I, he, she, it · ใช้กับ you, we, they' } ],
  rules:[ { en:'Finished in the past → verb 2.', th:'เรื่องที่จบแล้วในอดีต → กริยาช่อง 2',
            ok:'I [went] to the beach yesterday.', okTh:'เมื่อวานฉันไปทะเล', bad:'I [go] to the beach yesterday.' },
          { en:'Irregular verbs never take -ed: eat → ate, buy → bought.', th:'กริยาผิดปกติห้ามเติม -ed เช่น eat → ate, buy → bought',
            ok:'We [ate] pizza.', okTh:'เรากินพิซซ่า', bad:'We [eated] pizza.' },
          { en:"After did / didn't → the base verb.", th:"หลัง did / didn't → ใช้กริยาช่อง 1",
            ok:"He [didn't see] it.", okTh:'เขาไม่เห็นมัน', bad:"He [didn't saw] it." },
          { en:'be: I / he / she / it → was, you / we / they → were.', th:'be: I / he / she / it ใช้ was ส่วน you / we / they ใช้ were',
            ok:'They [were] at home.', okTh:'พวกเขาอยู่บ้าน', bad:'They [was] at home.' } ],
  clues:[ { s:'yesterday', sTh:'เมื่อวาน', en:'I called her yesterday', exTh:'เมื่อวานฉันโทรหาเธอ' }, { s:'last week', sTh:'สัปดาห์ที่แล้ว', en:'we met last week', exTh:'เราเจอกันสัปดาห์ที่แล้ว' },
          { s:'ago', sTh:'ที่แล้ว', en:'he left two hours ago', exTh:'เขาออกไปเมื่อสองชั่วโมงที่แล้ว' }, { s:'in 2019', sTh:'ในปี 2019', en:'she moved here in 2019', exTh:'เธอย้ายมาที่นี่ในปี 2019' } ],
  clueNote:{ en:'These words point to a finished time, so use verb 2.', th:'คำเหล่านี้บอกเวลาที่จบไปแล้ว จึงใช้กริยาช่อง 2' },
  tip:{ en:'Thai shows the past with เมื่อวาน or แล้ว and the verb stays the same. English changes the verb itself: go → went.',
        th:'ภาษาไทยบอกอดีตด้วยคำอย่าง "เมื่อวาน" หรือ "แล้ว" แต่กริยาไม่เปลี่ยน ภาษาอังกฤษต้องเปลี่ยนตัวกริยาเอง เช่น go → went' } },

{ unit:'tense', pos:'pastCont', chips:['pastCont','timeWord'], topic:'Past Continuous', th:'อดีตกำลังทำ (Past Continuous)',
  count:12, speed:1.3, spawn:2.9, maxAlive:3,
  items:[
    {t:'I [was sleeping] at 10 p.m. last night.', w:'I [was sleep] at 10 p.m. last night.'},
    {t:'They [were watching] TV when I arrived.', w:'They [was watching] TV when I arrived.'},
    {t:'She [was cooking] when the phone rang.', w:'She [cooking] when the phone rang.'},
    {t:"We [were playing] football at 5 o'clock yesterday.", w:"We [are playing] football at 5 o'clock yesterday."},
    {t:'While I [was walking] home, it started to rain.', w:'While I [walking] home, it started to rain.'},
    {t:'What [were] you doing last night?', w:'What [did] you doing last night?'},
    {t:"He [wasn't listening] to the teacher.", w:"He [didn't listening] to the teacher."},
    {t:'I [was having] dinner when you called.', w:'I [was have] dinner when you called.'},
    {t:'When the teacher came in, the students [were talking].', w:'When the teacher came in, the students [was talking].'},
    {t:'It [was raining] all morning.', w:'It [was rain] all morning.'},
  ],
  boss:[
    {t:'Last night I was reading and my parents were watching TV.', th:'เมื่อคืนฉันกำลังอ่านหนังสือ และพ่อแม่ของฉันกำลังดูทีวี',
     stages:[{pos:'timeWord', keys:['last','night']}, {pos:'pastCont', keys:['was','reading','were','watching']}], neutral:[]},
    {t:'While the zombie was sleeping, we were running away.', th:'ขณะที่ซอมบี้กำลังหลับ พวกเรากำลังวิ่งหนี',
     stages:[{pos:'timeWord', keys:['while']}, {pos:'pastCont', keys:['was','sleeping','were','running']}], neutral:['away']},
  ],
  q:{ en:'What was happening at that time?', th:'ตอนนั้นกำลังเกิดอะไรขึ้นอยู่?' },
  def:{ en:'The past continuous is for an action in progress at a time in the past: was / were + verb-ing. At 9 p.m. I was sleeping.',
        th:'Past Continuous ใช้กับเรื่องที่กำลังทำอยู่ ณ เวลาหนึ่งในอดีต: was / were + กริยาเติม -ing เช่น At 9 p.m. I was sleeping. (ตอนสามทุ่มฉันกำลังนอนหลับ)' },
  groups:[ { en:'I / he / she / it', th:'ใช้ was', words:'was reading · was cooking', wordsTh:'กำลังอ่าน (ตอนนั้น) · กำลังทำอาหาร (ตอนนั้น)' },
           { en:'you / we / they', th:'ใช้ were', words:'were playing · were watching', wordsTh:'กำลังเล่น (ตอนนั้น) · กำลังดู (ตอนนั้น)' },
           { en:'with when / while', th:'ใช้คู่กับ when / while', words:'when the phone rang · while I was walking', wordsTh:'ตอนที่โทรศัพท์ดัง · ขณะที่ฉันกำลังเดิน' } ],
  rules:[ { en:'Both parts: was / were + -ing.', th:'ต้องมีครบสองส่วน: was / were + -ing',
            ok:'I [was sleeping] at 10 p.m.', okTh:'ตอนสี่ทุ่มฉันกำลังนอนหลับ', bad:'I [was sleep] at 10 p.m.' },
          { en:'was for I / he / she / it, were for you / we / they.', th:'was ใช้กับ I / he / she / it ส่วน were ใช้กับ you / we / they',
            ok:'They [were watching] TV.', okTh:'พวกเขากำลังดูทีวี', bad:'They [was watching] TV.' },
          { en:'A long action (was …-ing) is cut by a short one (past simple) with when.', th:'เรื่องยาว (was …-ing) ถูกขัดด้วยเรื่องสั้น (Past Simple) โดยใช้ when',
            ok:'She [was cooking] when the phone [rang].', okTh:'เธอกำลังทำอาหารอยู่ตอนที่โทรศัพท์ดัง', bad:'She [cooking] when the phone rang.' },
          { en:'Questions and not: use was / were, not did.', th:'คำถามและปฏิเสธ: ใช้ was / were ไม่ใช่ did',
            ok:'What [were] you doing?', okTh:'ตอนนั้นคุณกำลังทำอะไรอยู่?', bad:'What [did] you doing?' } ],
  clues:[ { s:'at 8 p.m. last night', sTh:'ตอนสองทุ่มเมื่อคืน', en:'I was studying', exTh:'ฉันกำลังอ่านหนังสือ' }, { s:'when', sTh:'ตอนที่', en:'I was eating when you called', exTh:'ฉันกำลังกินอยู่ตอนที่คุณโทรมา' },
          { s:'while', sTh:'ขณะที่', en:'while she was driving', exTh:'ขณะที่เธอกำลังขับรถ' }, { s:'all morning', sTh:'ตลอดเช้า', en:'it was raining all morning', exTh:'ฝนตกตลอดเช้า' } ],
  clueNote:{ en:'A clock time in the past, "while", or a long action cut by "when" → was / were + -ing.', th:'เวลาที่ระบุในอดีต คำว่า while หรือเรื่องยาวที่ถูกขัดด้วย when → ใช้ was / were + -ing' },
  tip:{ en:'Thai uses กำลัง for both now and the past. English changes the helper: is cooking (now) → was cooking (then).',
        th:'ภาษาไทยใช้ "กำลัง" ทั้งตอนนี้และในอดีต แต่ภาษาอังกฤษต้องเปลี่ยนตัวช่วย is cooking (ตอนนี้) → was cooking (ตอนนั้น)' } },
);
